---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/vox/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp .htaccess admin.php branches.php brands.php brand-model-bootstrap.php calendar.php employees.php employee-status.php employee-patient-link.php kanban.php social-securities.php social-security-bootstrap.php service-types.php service-type-bootstrap.php sources.php source-bootstrap.php user-edit.php index.php item-new.php item-edit.php item-delete.php login.php logout.php profile.php patient-layout.php patients.php patients-export.php patient-results.php patient-form.php patient-delete.php patient-report-schema.php patient-report-status.php $DEPLOYPATH
