<?php
require __DIR__.'/config.php'; require_admin(); $message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='settings'){foreach(['hotel_name','retention_days','contact_email'] as $key){$s=db()->prepare('REPLACE INTO settings (setting_key,setting_value) VALUES (?,?)');$s->execute([$key,trim($_POST[$key]??'')]);}$message='Ayarlar kaydedildi.';}
 $tables=['location'=>['location_definitions','Yer'],'department'=>['department_definitions','Departman'],'storage'=>['storage_definitions','Depo']];
 foreach($tables as $prefix=>[$table,$label]){
  if($action===$prefix.'_add'){$name=trim($_POST[$prefix.'_name']??'');if($name==='')$error="$label adı boş bırakılamaz.";else try{$order=(int)db()->query("SELECT COALESCE(MAX(sort_order),0)+1 FROM $table")->fetchColumn();$s=db()->prepare("INSERT INTO $table (name,sort_order) VALUES (?,?)");$s->execute([$name,$order]);$message="$label tanımı eklendi.";}catch(PDOException $e){$error="Bu $label zaten tanımlı.";}}
  if($action===$prefix.'_delete'){$s=db()->prepare("DELETE FROM $table WHERE id=?");$s->execute([(int)($_POST[$prefix.'_id']??0)]);$message="$label tanımı silindi.";}
  if($action===$prefix.'_edit'){$id=(int)($_POST[$prefix.'_id']??0);$name=trim($_POST[$prefix.'_name']??'');if(!$id||$name==='')$error="$label adı boş bırakılamaz.";else try{$s=db()->prepare("UPDATE $table SET name=? WHERE id=?");$s->execute([$name,$id]);$message="$label tanımı güncellendi.";}catch(PDOException $e){$error="Bu $label zaten tanımlı.";}}
 }
 if($action==='item_definition_add'){$category=trim($_POST['item_category']??'');$name=trim($_POST['item_name']??'');if(!$category||!$name)$error='Kategori ve eşya adı zorunludur.';else try{$order=(int)db()->query('SELECT COALESCE(MAX(sort_order),0)+1 FROM item_definitions')->fetchColumn();$s=db()->prepare('INSERT INTO item_definitions (category,name,sort_order) VALUES (?,?,?)');$s->execute([$category,$name,$order]);$message='Eşya tanımı eklendi.';}catch(PDOException $e){$error='Bu eşya zaten tanımlı.';}}
 if($action==='item_definition_delete'){$s=db()->prepare('DELETE FROM item_definitions WHERE id=?');$s->execute([(int)($_POST['item_definition_id']??0)]);$message='Eşya tanımı silindi.';}
 if($action==='item_definition_edit'){$id=(int)($_POST['item_definition_id']??0);$category=trim($_POST['item_category']??'');$name=trim($_POST['item_name']??'');if(!$id||!$category||!$name)$error='Kategori ve eşya adı zorunludur.';else try{$s=db()->prepare('UPDATE item_definitions SET category=?,name=? WHERE id=?');$s->execute([$category,$name,$id]);$message='Eşya tanımı güncellendi.';}catch(PDOException $e){$error='Bu eşya zaten tanımlı.';}}
 if($action==='user'){$name=trim($_POST['name']??'');$email=trim(strtolower($_POST['email']??''));$password=$_POST['password']??'';$role=in_array($_POST['role']??'', ['Admin','User'],true)?$_POST['role']:'User';if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<6)$error='Kullanıcı bilgilerini kontrol edin.';else{$check=db()->prepare('SELECT id FROM users WHERE LOWER(email)=LOWER(?) LIMIT 1');$check->execute([$email]);if($check->fetch())$error='Bu e-posta adresi zaten kullanılıyor. Aynı e-posta ile ikinci kullanıcı oluşturulamaz.';else try{$s=db()->prepare('INSERT INTO users (name,email,password_hash,role,active) VALUES (?,?,?,?,1)');$s->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT),$role]);$message='Kullanıcı oluşturuldu.';}catch(PDOException $e){$error='Bu e-posta adresi zaten kullanılıyor. Aynı e-posta ile ikinci kullanıcı oluşturulamaz.';}}}
}
$settings=[];foreach(db()->query('SELECT setting_key,setting_value FROM settings') as $r)$settings[$r['setting_key']]=$r['setting_value'];
$locations=db()->query('SELECT id,name FROM location_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$departments=db()->query('SELECT id,name FROM department_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$storages=db()->query('SELECT id,name FROM storage_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$itemDefinitions=db()->query('SELECT id,category,name FROM item_definitions WHERE active=1 ORDER BY sort_order,category,name')->fetchAll();$users=db()->query('SELECT id,name,email,role,active FROM users ORDER BY id')->fetchAll();
function definition_list(array $rows,string $prefix,string $confirm):void{foreach($rows as $row){?><div><span><?=e($row['name'])?></span><div class="row-actions"><form method="post" onsubmit="return editDefinition(this,'<?=e($row['name'])?>')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$prefix?>_edit"><input type="hidden" name="<?=$prefix?>_id" value="<?=(int)$row['id']?>"><input type="hidden" name="<?=$prefix?>_name"><button class="edit-button">Düzenle</button></form><form method="post" onsubmit="return confirm('<?=e($confirm)?>')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$prefix?>_delete"><input type="hidden" name="<?=$prefix?>_id" value="<?=(int)$row['id']?>"><button class="delete-button">Sil</button></form></div></div><?php }}
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ayarlar | <?=APP_NAME?></title><link rel="icon" href="<?=url('assets/favicon.png')?>"><link rel="stylesheet" href="<?=url('assets/style.css')?>"><link rel="stylesheet" href="<?=url('assets/admin.css')?>"><link rel="stylesheet" href="<?=url('assets/admin-edit.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/fonts/fonts.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/icon/icomoon/style.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/css/bootstrap.min.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/css/styles.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce-lf.css')?>"><link rel="stylesheet" href="<?=url('assets/vuexy-inspired.css')?>"><link rel="stylesheet" href="<?=url('assets/green-buttons.css?v=20260712-3')?>"><script src="<?=url('assets/theme.js?v=20260712-2')?>"></script></head><body>
<header><div class="brand"><span class="brand-mark">K</span><span>KRP <b>Lost & Found</b></span></div><nav><a href="<?=url('index.php')?>">Eşyalar</a><a class="active" href="<?=url('admin.php')?>">Ayarlar</a></nav><div class="user"><span><?=e($_SESSION['user']['name'])?><small>Admin</small></span><a href="<?=url('logout.php')?>">Çıkış</a></div></header>
<main class="container narrow"><section class="title-row"><div><p class="eyebrow">ADMİN AYARLARI</p><h1>Yazılım ayarları</h1><p>Tüm tanımları ve kullanıcı yetkilerini tek ekrandan yönetin.</p></div></section>
<nav class="settings-menu"><a href="#genel">⚙ Genel</a><a href="#yerler">⌖ Bulunduğu yerler</a><a href="#departmanlar">▦ Departmanlar</a><a href="#depolar">▣ Depolar</a><a href="#esyalar">◆ Eşyalar</a><a href="#kullanicilar">♙ Kullanıcılar</a></nav>
<?php if($message):?><div class="success"><?=e($message)?></div><?php endif?><?php if($error):?><div class="alert"><?=e($error)?></div><?php endif?>
<form id="genel" class="panel form-grid settings-section" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="settings"><label>Otel adı<input name="hotel_name" value="<?=e($settings['hotel_name']??'Sofitel Istanbul Taksim')?>"></label><label>İletişim e-postası<input type="email" name="contact_email" value="<?=e($settings['contact_email']??'')?>"></label><label>Saklama süresi (gün)<input type="number" min="1" name="retention_days" value="<?=e($settings['retention_days']??90)?>"></label><div class="wide actions"><button class="primary">Kaydet</button></div></form>
<?php foreach([['yerler','Bulunduğu yer tanımları','location','Yeni yer adı',$locations],['departmanlar','Bulan departman tanımları','department','Yeni departman adı',$departments],['depolar','Depo tanımları','storage','Yeni depo adı',$storages]] as [$id,$title,$prefix,$placeholder,$rows]):?><section id="<?=$id?>" class="title-row admin-subtitle"><div><h1><?=$title?></h1></div></section><form class="panel location-add" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$prefix?>_add"><input name="<?=$prefix?>_name" placeholder="<?=$placeholder?>" required><button class="primary">Ekle</button></form><section class="panel location-list"><?php definition_list($rows,$prefix,'Bu tanım silinsin mi?')?></section><?php endforeach?>
<section id="esyalar" class="title-row admin-subtitle"><div><h1>Eşya tanımları</h1><p>Kategori ve eşya seçeneklerini yönetin.</p></div></section><form class="panel item-definition-add" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="item_definition_add"><input name="item_category" placeholder="Kategori" required><input name="item_name" placeholder="Eşya adı" required><button class="primary">Eşya ekle</button></form><section class="panel location-list"><?php foreach($itemDefinitions as $d):?><div><span><b><?=e($d['category'])?></b> – <?=e($d['name'])?></span><div class="row-actions"><form method="post" onsubmit="return editItem(this,'<?=e($d['category'])?>','<?=e($d['name'])?>')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="item_definition_edit"><input type="hidden" name="item_definition_id" value="<?=(int)$d['id']?>"><input type="hidden" name="item_category"><input type="hidden" name="item_name"><button class="edit-button">Düzenle</button></form><form method="post" onsubmit="return confirm('Bu eşya tanımı silinsin mi?')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="item_definition_delete"><input type="hidden" name="item_definition_id" value="<?=(int)$d['id']?>"><button class="delete-button">Sil</button></form></div></div><?php endforeach?></section>
<section id="kullanicilar" class="title-row admin-subtitle"><div><h1>Kullanıcılar</h1><p>Admin ayarları yönetir; User uygulamayı kullanır.</p></div></section><form class="panel form-grid" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="user"><label>Ad soyad<input name="name" required></label><label>E-posta<input type="email" name="email" required></label><label>Şifre<input type="password" name="password" minlength="6" required></label><label>Rol<select name="role"><option>User</option><option>Admin</option></select></label><div class="wide actions"><button class="primary">Kullanıcı ekle</button></div></form><section class="panel users-panel"><table><thead><tr><th>Ad soyad</th><th>E-posta</th><th>Rol</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?=e($u['name'])?></td><td><?=e($u['email'])?></td><td><span class="role-badge"><?=e($u['role'])?></span></td><td><?=$u['active']?'Aktif':'Pasif'?></td><td><?php if($u['role']==='User'):?><a class="edit-button user-edit-link" href="<?=url('user-edit.php?id='.(int)$u['id'])?>">Düzenle / Şifre</a><?php else:?><span class="admin-protected">Yönetici</span><?php endif?></td></tr><?php endforeach?></tbody></table></section>
</main><script>function editDefinition(form,current){const value=prompt('Yeni adı girin:',current);if(value===null||!value.trim())return false;form.querySelector('input[name$="_name"]').value=value.trim();return true}function editItem(form,category,name){const newCategory=prompt('Kategori:',category);if(newCategory===null)return false;const newName=prompt('Eşya adı:',name);if(newName===null||!newCategory.trim()||!newName.trim())return false;form.item_category.value=newCategory.trim();form.item_name.value=newName.trim();return true}</script></body></html>
