<?php
declare(strict_types=1);
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
require __DIR__ . '/config.php';
require_admin();
require __DIR__ . '/anamnesis-bootstrap.php';
require __DIR__ . '/patient-layout.php';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    $layout = (string)($_POST['designer_layout'] ?? '');
    if (strlen($layout) > 60000 || trim($layout) === '') { http_response_code(422); header('Content-Type: application/json'); echo json_encode(['success'=>false]); exit; }
    save_anamnesis_print_settings(['designer_layout' => $layout]);
    header('Content-Type: application/json'); echo json_encode(['success'=>true]); exit;
}
$designerQuestions = array_values(array_filter(anamnesis_question_definitions(), fn($q) => (int)$q['active'] === 1));
$designerFields = array_values(array_filter(anamnesis_text_field_definitions(), fn($f) => (int)$f['active'] === 1));
$designerSourceLabels = [];
foreach ($designerQuestions as $question) {
    $designerSourceLabels['question-' . (int)$question['id']] = mb_strtoupper((string)$question['name'], 'UTF-8');
    if (trim((string)($question['detail_label'] ?? '')) !== '') $designerSourceLabels['question-' . (int)$question['id'] . '-detail'] = mb_strtoupper((string)$question['detail_label'], 'UTF-8');
}
foreach ($designerFields as $field) $designerSourceLabels['field-' . (int)$field['id']] = mb_strtoupper((string)$field['name'], 'UTF-8');
patient_header('Anamnez Görsel Tasarımcı', 'settings');
?>
<main class="designer">
  <header><div><h1>Anamnez Görsel Tasarımcı</h1><p>Blokları A4 sayfasına sürükleyin; seçili bloğu taşıyın ve köşesinden boyutlandırın.</p></div><a href="<?=url('anamnesis-questions.php')?>">Anamnez ayarlarına dön</a></header>
  <div class="question-blocks"><?php foreach($designerQuestions as $question): ?><button draggable="true" data-type="text" data-source-key="question-<?= (int)$question['id'] ?>"><?=e(mb_strtoupper((string)$question['name'], 'UTF-8'))?></button><?php if (trim((string)($question['detail_label'] ?? '')) !== ''): ?><button draggable="true" data-type="text" data-source-key="question-<?= (int)$question['id'] ?>-detail"><?=e(mb_strtoupper((string)$question['detail_label'], 'UTF-8'))?></button><?php endif; ?><?php endforeach; ?><?php foreach($designerFields as $field): ?><button draggable="true" data-type="text" data-source-key="field-<?= (int)$field['id'] ?>"><?=e(mb_strtoupper((string)$field['name'], 'UTF-8'))?></button><?php endforeach; ?></div>
  <div class="designer-layout">
    <aside class="toolbox"><h2>Bloklar</h2><button draggable="true" data-type="title">Başlık</button><button draggable="true" data-type="patient">Hasta / Tarih</button><button draggable="true" data-type="text">Metin Alanı</button><button draggable="true" data-type="answer">Cevap Kutucuğu</button><button draggable="true" data-type="logo">Şirket Logosu</button><hr><h2>Seçili alan</h2><label>Yazı boyutu<input id="font-size" type="number" min="8" max="48" value="13"></label><label>En (%)<input id="block-width" type="number" min="5" max="100" step="1" value="45"></label><label>Boy (%)<input id="block-height" type="number" min="3" max="100" step="1" value="7"></label><label>Yazı rengi<input id="text-color" type="color" value="#182438"></label><label>Kenar<input id="border-color" type="color" value="#19a94b"></label><div class="align-controls"><button type="button" data-align="left">Sola</button><button type="button" data-align="center">Ortala</button><button type="button" data-align="right">Sağa</button></div><div class="align-controls"><button type="button" data-vertical-align="start">Üste</button><button type="button" data-vertical-align="center">Dikey Ortala</button><button type="button" data-vertical-align="end">Alta</button></div><button type="button" id="delete-selected" class="delete-selected">Seçili Alanı Sil</button><p>Seçili kutuyu sürükleyin; sağ-alt köşesinden veya En / Boy alanlarından ölçülendirin. Kılavuz çizgilerine hizalanır.</p></aside>
    <section class="canvas-area"><div id="a4" aria-label="A4 tasarım alanı"><div class="design-block title" data-type="title" style="left:7%;top:6%;width:55%;height:8%">VOX İ.M. - HASTA KARTI<i></i></div><div class="design-block" data-type="patient" style="left:7%;top:16%;width:86%;height:5%">Hasta Ad Soyad <span>Tarih</span><i></i></div><div class="design-block logo" data-type="logo" style="left:34%;top:87%;width:32%;height:5%">Şirket Logosu<i></i></div></div></section>
  </div>
  <footer><button type="button" id="preview">A4 Ön Görüntü</button><button type="button" id="save">Tasarımı Kaydet</button></footer>
</main>
<style>
.question-blocks{display:flex;gap:6px;flex-wrap:wrap;max-height:156px;overflow-y:auto;overscroll-behavior:contain;margin:0 0 16px;padding:8px;border:1px solid #d9dde5;border-radius:8px;background:#fff}.question-blocks button{padding:7px 9px;border:1px solid #bde0c7;background:#fff;border-radius:5px;color:#14743a;cursor:grab}
.toolbox label{display:block;font-size:12px;margin:9px 0;color:#4b5361}.toolbox input{display:block;width:100%;margin-top:4px;box-sizing:border-box}
body .designer{padding-top:96px!important}
.designer{max-width:1280px;margin:0 auto;padding:28px 22px}.designer>header{display:flex;justify-content:space-between;gap:16px;align-items:start;margin-bottom:20px}.designer h1{margin:0;font-size:25px}.designer header p{margin:7px 0;color:#6d6875}.designer>header>a{display:flex!important;align-items:center;justify-content:center;box-sizing:border-box;min-width:190px;min-height:48px;border:0!important;border-radius:7px;background:#19a94b!important;color:#fff!important;text-decoration:none!important;font:700 14px/1.15 Arial!important;text-align:center;padding:11px 16px!important}.designer footer button{border:0;border-radius:7px;background:#19a94b;color:white;text-decoration:none;font-weight:700;padding:11px 16px}.designer-layout{display:grid;grid-template-columns:210px 1fr;gap:18px}.toolbox{background:#fff;border:1px solid #d9dde5;border-radius:8px;padding:15px;height:max-content}.toolbox h2{font-size:16px;margin:0 0 12px}.toolbox button{width:100%;display:block;margin:8px 0;padding:11px;border:1px solid #bde0c7;border-radius:6px;background:#f5fbf6;color:#14743a;font-weight:700;cursor:grab;text-align:left}.toolbox .align-controls{display:flex;gap:4px;margin:10px 0}.toolbox .align-controls button{width:auto;flex:1;margin:0;padding:8px;text-align:center;cursor:pointer}.toolbox .delete-selected{background:#e64d5c;border-color:#e64d5c;color:#fff;cursor:pointer}.toolbox p{font-size:12px;color:#6d6875;line-height:1.5}.canvas-area{overflow:auto;padding:10px;background:#edf0f4;border-radius:8px;min-height:720px}#a4{position:relative;width:min(100%,680px);aspect-ratio:210/297;margin:auto;background-color:#fff;background-image:linear-gradient(to right,#18a94b33 1px,transparent 1px),linear-gradient(to bottom,#18a94b33 1px,transparent 1px);background-size:1% 1%;box-shadow:0 2px 10px #18243833;border:1px solid #9da6b5;overflow:hidden}.design-block{position:absolute;box-sizing:border-box;border:1px dashed #19a94b;background:#f4fff7;color:#182438;padding:8px;font:13px Arial;cursor:move;user-select:none;overflow:hidden}.design-block.selected{border:2px solid #14843c;background:#e7f7eb}.design-block span{float:right}.design-block i{position:absolute;right:-5px;bottom:-5px;width:12px;height:12px;background:#19a94b;border:2px solid #fff;border-radius:2px;cursor:nwse-resize}.title{font-size:22px;font-weight:700;color:#14843c}.questions{background:#fbfdfb;color:#14743a;text-align:center;padding-top:25%}.answer{display:flex;align-items:center;justify-content:center;white-space:nowrap;font-size:11px!important;font-weight:400}.logo{text-align:center}.designer footer{display:flex;justify-content:flex-end;gap:10px;margin-top:16px}.designer footer #preview{background:#30435d}@media(max-width:760px){.designer{padding:18px 10px}.designer>header{flex-direction:column}.designer-layout{grid-template-columns:1fr}.toolbox{display:flex;gap:7px;flex-wrap:wrap}.toolbox h2,.toolbox p,.toolbox hr{width:100%}.toolbox button{width:auto;margin:0}.canvas-area{min-height:auto;padding:5px}}
</style>
<script>
(() => {
  const canvas=document.getElementById('a4'); let selected=null,drag=null;
  const sourceLabels=<?=json_encode($designerSourceLabels, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>;
  const widthInput=document.getElementById('block-width'),heightInput=document.getElementById('block-height');
  const snap=value=>Math.round(value);
  document.getElementById('font-size').oninput=e=>{if(selected){const size=Math.max(8,Math.min(48,Number(e.target.value)||13));selected.style.fontSize=size+'px';e.target.value=size}};
  document.getElementById('text-color').oninput=e=>{if(selected)selected.style.color=e.target.value};
  document.getElementById('border-color').oninput=e=>{if(selected)selected.style.borderColor=e.target.value};
  document.querySelectorAll('.align-controls button[data-align]').forEach(button=>button.onclick=()=>{if(!selected)return;selected.style.textAlign=button.dataset.align;persist()});
  document.querySelectorAll('.align-controls button[data-vertical-align]').forEach(button=>button.onclick=()=>{if(!selected)return;selected.style.display='grid';selected.style.alignContent=button.dataset.verticalAlign;persist()});
  widthInput.oninput=e=>{if(selected)selected.style.width=Math.max(5,Math.min(100,Number(e.target.value)||5))+'%'};
  heightInput.oninput=e=>{if(selected)selected.style.height=Math.max(3,Math.min(100,Number(e.target.value)||3))+'%'};
  function editAnswer(block){if(block.querySelector('select'))return;const handle=block.querySelector('i'),picker=document.createElement('select');picker.innerHTML='<option value="yes_no">Evet / Hayır</option><option value="var_yok">Var / Yok</option>';picker.value=block.textContent.includes('Var')?'var_yok':'yes_no';picker.addEventListener('pointerdown',event=>event.stopPropagation());block.textContent='';block.appendChild(picker);if(handle)block.appendChild(handle);picker.focus();const apply=()=>{const selectedType=picker.value;block.textContent=selectedType==='var_yok'?'☐ Var':'☐ Evet';if(handle)block.appendChild(handle)};picker.addEventListener('change',apply);picker.addEventListener('blur',apply)}
  canvas.addEventListener('dblclick',e=>{const block=e.target.closest('.design-block');if(!block)return;e.preventDefault();if(block.classList.contains('answer')){editAnswer(block);return}block.contentEditable='true';block.focus()});
  const label={title:'VOX İ.M. - HASTA KARTI',patient:'Hasta Ad Soyad - Tarih',questions:'Anamnez Soruları',text:'Metin Alanı',answer:'☐ Evet',logo:'Şirket Logosu'};
  function select(el){document.querySelectorAll('.design-block').forEach(x=>x.classList.remove('selected'));selected=el;el.classList.add('selected');document.getElementById('font-size').value=Math.round(parseFloat(getComputedStyle(el).fontSize)||13);widthInput.value=Math.round(parseFloat(el.style.width)||el.getBoundingClientRect().width/canvas.getBoundingClientRect().width*100);heightInput.value=Math.round(parseFloat(el.style.height)||el.getBoundingClientRect().height/canvas.getBoundingClientRect().height*100)}
  function persist(){localStorage.setItem('vox-anamnesis-layout',canvas.innerHTML)}
  function removeSelected(){if(!selected)return;selected.remove();selected=null;persist()}
  document.getElementById('delete-selected').onclick=removeSelected;
  document.addEventListener('keydown',e=>{if(e.key==='Delete'&&selected&&document.activeElement?.contentEditable!=='true'){e.preventDefault();removeSelected()}});
  function add(type,x,y,customLabel='',sourceKey=''){const count=canvas.querySelectorAll('.design-block').length;if(!Number.isFinite(x))x=8+(count%4)*12;if(!Number.isFinite(y))y=8+(count%5)*9;const el=document.createElement('div');el.className='design-block '+type;el.dataset.type=type;if(sourceKey)el.dataset.sourceKey=sourceKey;const width=type==='questions'?70:type==='answer'?18:45, height=type==='questions'?35:type==='answer'?4:7;el.style.cssText=`left:${x}%;top:${y}%;width:${width}%;height:${height}%`;el.innerHTML=(customLabel||label[type]||'Metin Alanı')+'<i></i>';canvas.appendChild(el);select(el);persist()}
  document.querySelectorAll('.toolbox button[data-type]').forEach(b=>{b.addEventListener('click',()=>add(b.dataset.type));b.addEventListener('dragstart',e=>e.dataTransfer.setData('type',b.dataset.type))});
  function blockText(block){const copy=block.cloneNode(true);copy.querySelectorAll('i,select').forEach(node=>node.remove());return copy.textContent.trim()}
  function setBlockText(block,text){const handle=block.querySelector('i');block.textContent=text;if(handle)block.appendChild(handle)}
  function normalizedText(text){return String(text).toLocaleUpperCase('tr-TR').replace(/[^\p{L}\p{N}]+/gu,'')}
  function migrateLegacyBlocks(){const lookup=Object.entries(sourceLabels),taken=new Set([...canvas.querySelectorAll('.design-block[data-source-key]')].map(block=>block.dataset.sourceKey));let migrated=false;canvas.querySelectorAll('.design-block.text:not([data-source-key])').forEach(block=>{const match=lookup.find(([key,text])=>!taken.has(key)&&normalizedText(text)===normalizedText(blockText(block)));if(match){block.dataset.sourceKey=match[0];taken.add(match[0]);migrated=true}});return migrated}
  function consumeSource(sourceKey,text){const source=[...document.querySelectorAll('.question-blocks button')].find(button=>sourceKey?button.dataset.sourceKey===sourceKey:button.textContent.trim()===text);if(source)source.remove()}
  function syncSourceLabels(){canvas.querySelectorAll('.design-block[data-source-key]').forEach(block=>{const text=sourceLabels[block.dataset.sourceKey];if(text)setBlockText(block,text)})}
  function consumeUsedSources(){const usedKeys=new Set([...canvas.querySelectorAll('.design-block[data-source-key]')].map(block=>block.dataset.sourceKey)),legacyCounts=new Map();canvas.querySelectorAll('.design-block.text:not([data-source-key])').forEach(block=>{const text=blockText(block);legacyCounts.set(text,(legacyCounts.get(text)||0)+1)});document.querySelectorAll('.question-blocks button').forEach(button=>{const text=button.textContent.trim();if(usedKeys.has(button.dataset.sourceKey)){button.remove();return}const count=legacyCounts.get(text)||0;if(count){legacyCounts.set(text,count-1);button.remove()}})}
  document.querySelectorAll('.question-blocks button').forEach(b=>{const text=b.textContent.trim(),sourceKey=b.dataset.sourceKey;b.addEventListener('dragstart',e=>{e.dataTransfer.setData('type','text');e.dataTransfer.setData('label',text);e.dataTransfer.setData('sourceKey',sourceKey)});b.addEventListener('click',()=>{add('text',undefined,undefined,text,sourceKey);consumeSource(sourceKey,text)})});
  canvas.addEventListener('dragover',e=>e.preventDefault());canvas.addEventListener('drop',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),type=e.dataTransfer.getData('type')||'text',text=e.dataTransfer.getData('label')||'',sourceKey=e.dataTransfer.getData('sourceKey')||'';add(type,Math.round((e.clientX-r.left)/r.width*100),Math.round((e.clientY-r.top)/r.height*100),text,sourceKey);if(text)consumeSource(sourceKey,text)});
  canvas.addEventListener('pointerdown',e=>{const el=e.target.closest('.design-block');if(!el)return;select(el);const r=canvas.getBoundingClientRect(),b=el.getBoundingClientRect();drag={el,resize:e.target.tagName==='I',sx:e.clientX,sy:e.clientY,x:(b.left-r.left)/r.width*100,y:(b.top-r.top)/r.height*100,w:b.width/r.width*100,h:b.height/r.height*100};el.setPointerCapture(e.pointerId)});
  canvas.addEventListener('click',e=>{const el=e.target.closest('.design-block');if(el)select(el)});
  canvas.addEventListener('pointermove',e=>{if(!drag)return;const r=canvas.getBoundingClientRect(),dx=(e.clientX-drag.sx)/r.width*100,dy=(e.clientY-drag.sy)/r.height*100;if(drag.resize){drag.el.style.width=snap(Math.max(12,drag.w+dx))+'%';drag.el.style.height=snap(Math.max(4,drag.h+dy))+'%'}else{drag.el.style.left=snap(Math.max(0,Math.min(95-drag.w,drag.x+dx)))+'%';drag.el.style.top=snap(Math.max(0,Math.min(95-drag.h,drag.y+dy)) )+'%'}widthInput.value=Math.round(parseFloat(drag.el.style.width));heightInput.value=Math.round(parseFloat(drag.el.style.height))});canvas.addEventListener('pointerup',()=>{if(drag)persist();drag=null});
  document.getElementById('preview').onclick=()=>{const w=window.open('','_blank');const css='@page{size:A4;margin:0}body{margin:0;background:#fff}#a4{width:210mm;height:297mm;position:relative;margin:0 auto;background:#fff}.design-block{position:absolute;box-sizing:border-box;border:1px solid #182438;padding:7px;font:10pt Arial;color:#182438;overflow:hidden}.design-block span{float:right}.title{font-size:20pt;font-weight:700;color:#14843c}.questions{text-align:center;padding-top:25%}.answer{display:flex;align-items:center;justify-content:center;white-space:nowrap;font-weight:700}.logo{text-align:center}.design-block i{display:none}';w.document.write('<!doctype html><html><head><meta charset="utf-8"><style>'+css+'</style></head><body>'+canvas.outerHTML+'</body></html>');w.document.close()};
  document.getElementById('save').onclick=async()=>{persist();const data=new URLSearchParams({csrf:<?=json_encode(csrf())?>,designer_layout:canvas.innerHTML});const response=await fetch(location.href,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body:data});if(!response.ok)throw new Error('Tasarım kaydedilemedi.');alert('Tasarım sunucuda kaydedildi.')};const serverLayout=<?=json_encode((string)anamnesis_print_settings()['designer_layout'], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;const old=localStorage.getItem('vox-anamnesis-layout')||serverLayout;if(old)canvas.innerHTML=old;canvas.querySelectorAll('.design-block.questions').forEach(block=>block.remove());const migrated=migrateLegacyBlocks();syncSourceLabels();consumeUsedSources();if(migrated)persist();
})();
</script>
<?php patient_footer(); ?>
