<?php
declare(strict_types=1);
require __DIR__ . '/config.php';
require_admin();
require __DIR__ . '/anamnesis-bootstrap.php';
require __DIR__ . '/patient-layout.php';

$pdo = db(); $message = ''; $error = '';
$editId = (int)($_GET['edit'] ?? $_POST['anamnesis_question_id'] ?? 0);
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $action = (string)($_POST['action'] ?? 'save_question'); $id = (int)($_POST['anamnesis_question_id'] ?? 0);
    if ($action === 'save_print_settings') {
        $headerColor = preg_match('/^#[0-9a-fA-F]{6}$/', (string)($_POST['header_color'] ?? '')) ? (string)$_POST['header_color'] : '#14843c';
        save_anamnesis_print_settings([
            'title' => mb_substr(trim((string)($_POST['print_title'] ?? 'VOX İ.M. - HASTA KARTI')), 0, 120),
            'header_color' => $headerColor,
            'font_size' => (string)max(9, min(16, (int)($_POST['font_size'] ?? 11))),
            'question_font_size' => (string)max(9, min(16, (int)($_POST['question_font_size'] ?? 11))),
            'page_margin' => (string)max(8, min(42, (int)($_POST['page_margin'] ?? 20))),
            'question_width' => (string)max(32, min(65, (int)($_POST['question_width'] ?? 46))),
            'yes_width' => (string)max(7, min(20, (int)($_POST['yes_width'] ?? 12))),
            'detail_width' => (string)max(12, min(30, (int)($_POST['detail_width'] ?? 20))),
            'row_height' => (string)max(20, min(50, (int)($_POST['row_height'] ?? 27))),
            'notes_height' => (string)max(28, min(80, (int)($_POST['notes_height'] ?? 37))),
            'footer_height' => (string)max(24, min(80, (int)($_POST['footer_height'] ?? 34))),
            'line_width' => (string)max(1, min(3, (int)($_POST['line_width'] ?? 1))),
            'layout' => mb_substr((string)($_POST['layout'] ?? ''), 0, 2000),
        ]);
        $message = 'Yazıcı çıktısı tasarımı kaydedildi.';
    } elseif ($action === 'delete_question') {
        $pdo->prepare('DELETE FROM anamnesis_question_definitions WHERE id=?')->execute([$id]); $message = 'Anamnez sorusu silindi.';
    } else {
        $name = trim((string)($_POST['name'] ?? '')); $active = isset($_POST['active']) ? 1 : 0; $sort = (int)($_POST['sort_order'] ?? 0);
        if ($name === '') $error = 'Soru alanı zorunludur.';
        else {
            $duplicate = $pdo->prepare('SELECT id FROM anamnesis_question_definitions WHERE name=? AND id<>?'); $duplicate->execute([$name, $id]);
            if ($duplicate->fetchColumn()) $error = 'Bu soru zaten kayıtlı.';
            elseif ($id) { $pdo->prepare('UPDATE anamnesis_question_definitions SET name=?,detail_label=?,active=?,sort_order=? WHERE id=?')->execute([$name,trim((string)($_POST['detail_label'] ?? '')),$active,$sort,$id]); $message='Anamnez sorusu güncellendi.'; }
            else { $pdo->prepare('INSERT INTO anamnesis_question_definitions(name,detail_label,active,sort_order) VALUES(?,?,?,?)')->execute([$name,trim((string)($_POST['detail_label'] ?? '')),$active,$sort]); $message='Anamnez sorusu eklendi.'; }
        }
    }
}
$edit = ['id'=>0,'name'=>'','detail_label'=>'','active'=>1,'sort_order'=>0];
if ($editId) { $statement=$pdo->prepare('SELECT * FROM anamnesis_question_definitions WHERE id=?'); $statement->execute([$editId]); $edit=$statement->fetch() ?: $edit; }
$rows = anamnesis_question_definitions();
$printSettings = anamnesis_print_settings();
patient_header('Ayarlar - Anamnez', 'settings');
?>
<main class="patient-container personnel-page"><nav class="settings-tabs"></nav>
  <?php if($message):?><p class="vox-message success"><?=e($message)?></p><?php endif?><?php if($error):?><p class="vox-message error"><?=e($error)?></p><?php endif?>
  <details class="vuexy-form-card definition-accordion"<?=($editId||$error)?' open':''?>><summary class="form-card-title"><span><h1><?=$editId?'Anamnez Sorusu Düzenle':'Yeni Anamnez Sorusu'?></h1><p>Hasta kartındaki Evet / Hayır sorularını yönetin.</p></span><i class="definition-chevron" aria-hidden="true"></i></summary>
    <form method="post" class="personnel-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_question"><input type="hidden" name="anamnesis_question_id" value="<?=(int)$edit['id']?>"><label>Soru<input name="name" maxlength="512" value="<?=e($edit['name'])?>" required></label><label>Açıklama Alanı Başlığı<input name="detail_label" maxlength="190" placeholder="Örn. Ne kadar süre" value="<?=e((string)$edit['detail_label'])?>"></label><label>Sıra<input type="number" name="sort_order" value="<?=(int)$edit['sort_order']?>"></label><label class="personnel-check"><span>Durum</span><span><input type="checkbox" name="active" <?=$edit['active']?'checked':''?>> Aktif</span></label><div class="personnel-actions"><button type="submit"><?=$editId?'Güncelle':'Kaydet'?></button><?php if($editId):?><a class="edit-definition" href="<?=url('anamnesis-questions.php')?>">İptal</a><?php endif?></div></form>
  </details>
  <section class="vuexy-form-card"><header class="form-card-title"><h2>Anamnez Soruları</h2><p><?=count($rows)?> kayıt</p></header><div class="table-responsive"><table class="personnel-table anamnesis-question-table"><thead><tr><th class="question-column">Soru</th><th class="detail-column">Açıklama Alanı</th><th class="sort-column">Sıra</th><th class="status-column">Durum</th><th class="actions-column">İşlemler</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td class="question-column"><?=e($row['name'])?></td><td class="detail-column"><?=e((string)$row['detail_label'])?:'—'?></td><td class="sort-column"><?=(int)$row['sort_order']?></td><td class="status-column"><span class="status-pill <?=$row['active']?'active':'passive'?>"><?=$row['active']?'Aktif':'Pasif'?></span></td><td class="actions-column"><a class="edit-definition" href="<?=url('anamnesis-questions.php?edit='.(int)$row['id'])?>">Düzenle</a><form method="post" class="inline" onsubmit="return confirm('Bu soru silinsin mi?')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_question"><input type="hidden" name="anamnesis_question_id" value="<?=(int)$row['id']?>"><button type="submit" class="delete-definition">Sil</button></form></td></tr><?php endforeach?></tbody></table></div></section>
  <details class="vuexy-form-card definition-accordion"><summary class="form-card-title"><span><h2>Yazıcı Çıktısı Tasarımı</h2><p>Anamnez hasta kartının yazdırılmış görünümünü düzenleyin.</p></span><i class="definition-chevron" aria-hidden="true"></i></summary>
    <form method="post" class="personnel-form print-design-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_print_settings"><input type="hidden" name="layout" value="<?=e($printSettings['layout'])?>">
      <div class="print-settings-panel">
        <h3>Sayfa ve başlık</h3>
        <label>Başlık<input name="print_title" maxlength="120" value="<?=e($printSettings['title'])?>" required></label>
        <label>Başlık rengi<input type="color" name="header_color" value="<?=e($printSettings['header_color'])?>"></label>
        <label>Sayfa kenar boşluğu (mm)<input type="number" name="page_margin" min="8" max="42" value="<?=e($printSettings['page_margin'])?>"></label>
        <label>Gövde yazı boyutu<input type="number" name="font_size" min="9" max="16" value="<?=e($printSettings['font_size'])?>"></label>
        <label>Soru yazı boyutu<input type="number" name="question_font_size" min="9" max="16" value="<?=e($printSettings['question_font_size'])?>"></label>
      </div>
      <div class="print-settings-panel">
        <h3>Tablo ölçüleri</h3>
        <label>Soru sütunu (%)<input type="number" name="question_width" min="32" max="65" value="<?=e($printSettings['question_width'])?>"></label>
        <label>Evet sütunu (%)<input type="number" name="yes_width" min="7" max="20" value="<?=e($printSettings['yes_width'])?>"></label>
        <label>Açıklama sütunu (%)<input type="number" name="detail_width" min="12" max="30" value="<?=e($printSettings['detail_width'])?>"></label>
        <label>Soru satırı yüksekliği (px)<input type="number" name="row_height" min="20" max="50" value="<?=e($printSettings['row_height'])?>"></label>
        <label>Not alanı yüksekliği (px)<input type="number" name="notes_height" min="28" max="80" value="<?=e($printSettings['notes_height'])?>"></label>
        <label>Alt bilgi yüksekliği (px)<input type="number" name="footer_height" min="24" max="80" value="<?=e($printSettings['footer_height'])?>"></label>
        <label>Çizgi kalınlığı (px)<input type="number" name="line_width" min="1" max="3" value="<?=e($printSettings['line_width'])?>"></label>
      </div>
      <p class="designer-help">Değerleri değiştirip <strong>Ön Görüntü</strong> ile A4 sonucunu kontrol edin. Beğendiğiniz sonucu <strong>Tasarımı Kaydet</strong> ile kalıcılaştırın.</p>
      <div class="personnel-actions"><button type="submit">Tasarımı Kaydet</button><button type="button" class="print-preview-button">Ön Görüntü</button></div>
    </form>
  </details>
</main>
<style>.personnel-page{width:100%;max-width:1000px;min-height:100vh;margin:0 auto;padding:46px 20px 48px}.settings-tabs{display:flex;gap:8px;margin-bottom:20px;flex-wrap:wrap}.vuexy-form-card{background:#fff;border:1px solid #e1e2e8;border-radius:10px;margin-bottom:24px;box-shadow:0 3px 12px #1e283c0f;overflow:hidden}.form-card-title{display:block;padding:22px 24px;border-bottom:1px solid #e1e2e8}.form-card-title h1,.form-card-title h2{margin:0 0 5px;font-size:21px}.form-card-title p{margin:0;color:#7b7b8d}.personnel-form{display:flex;gap:16px;align-items:end;padding:24px;flex-wrap:wrap}.personnel-form label{display:flex;flex-direction:column;gap:7px}.personnel-form input:not([type=checkbox]){height:43px;min-width:240px;border:1px solid #d2d2dc;border-radius:7px;padding:0 12px}.personnel-check{flex-direction:row!important;align-items:center;height:43px}.personnel-actions button,.edit-definition,.delete-definition{border:0;border-radius:7px;padding:11px 18px;text-decoration:none;font-weight:700;background:#19a94b;color:#fff}.delete-definition{background:#df4a4a;margin-left:8px}.inline{display:inline}.personnel-table{width:100%;border-collapse:collapse;min-width:0!important;table-layout:fixed}.personnel-table th,.personnel-table td{padding:14px 12px;border-bottom:1px solid #e1e2e8;text-align:left;white-space:normal}.personnel-table th:nth-child(1){width:auto}.personnel-table th:nth-child(2){width:46px}.personnel-table th:nth-child(3){width:64px}.personnel-table th:nth-child(4){width:145px}.personnel-table td:last-child{white-space:nowrap}.table-responsive{overflow:visible}.vox-message{padding:13px 16px;margin:16px 0;border-radius:7px}.vox-message.success{background:#daf5e3;color:#0d7130}.vox-message.error{background:#ffe3e3;color:#a21d1d}.definition-accordion>summary{position:relative;display:flex;align-items:center;padding-right:64px;cursor:pointer;list-style:none}.definition-chevron{position:absolute;right:24px;top:50%;font-style:normal;font-size:20px;transform:translateY(-50%)}.definition-chevron::before{content:'>'}.definition-accordion[open] .definition-chevron{transform:translateY(-50%) rotate(90deg)}@media(max-width:760px){.personnel-page{padding:24px 12px}.personnel-table th:nth-child(2),.personnel-table td:nth-child(2),.personnel-table th:nth-child(3),.personnel-table td:nth-child(3){display:none}.personnel-table th:nth-child(4){width:130px}.personnel-table th,.personnel-table td{padding:12px 9px}.edit-definition,.delete-definition{padding:9px 10px}}</style>
<style>
.print-design-form{align-items:flex-start}.a4-designer{position:relative;flex:0 0 420px;width:420px;height:594px;max-width:100%;border:1px solid #aeb5c3;background:#fff;box-shadow:0 2px 12px #1e283c18;overflow:hidden}.a4-guides{position:absolute;inset:0;pointer-events:none;background-image:linear-gradient(to right,rgba(25,169,75,.22) 1px,transparent 1px),linear-gradient(to bottom,rgba(25,169,75,.22) 1px,transparent 1px);background-size:21px 21px}.a4-designer::before{content:'A4 · 210 × 297 mm';position:absolute;right:10px;bottom:8px;color:#8b8a95;font-size:11px}.design-block{position:absolute;z-index:1;display:flex;align-items:center;justify-content:center;min-width:82px;padding:7px 10px;border:1px dashed #14843c;border-radius:4px;background:#ecf8f0;color:#126c32;font-size:12px;font-weight:700;cursor:grab;user-select:none}.design-block:active{cursor:grabbing}.design-block-large{width:270px;height:270px}.design-resize-handle{position:absolute;right:-5px;bottom:-5px;width:11px;height:11px;border:1px solid #14843c;border-radius:2px;background:#fff;cursor:nwse-resize}.designer-help{flex-basis:100%;margin:0;color:#6e6c7b;font-size:13px}.print-preview-button{background:#30435d!important}.print-preview-modal[hidden]{display:none!important}.print-preview-modal{position:fixed;inset:0;z-index:3000;display:grid;place-items:center;padding:20px;background:rgba(25,28,38,.58)}.print-preview-sheet{position:relative;width:min(620px,100%);aspect-ratio:210/297;background:#fff;box-shadow:0 18px 46px rgba(0,0,0,.3);overflow:hidden}.print-preview-sheet button{position:absolute;right:12px;top:8px;border:0;background:transparent;font-size:25px;cursor:pointer}.print-preview-block{position:absolute;border:1px dashed #cbd3ce;padding:6px 8px;color:#23343a;font-size:12px;overflow:hidden}.print-preview-block.header{font-weight:700}.print-preview-block.questions{width:62%;height:47%;line-height:1.65}@media(max-width:760px){.a4-designer{flex-basis:100%;width:100%;height:calc((100vw - 48px) * 1.414)}}
.anamnesis-question-table,.anamnesis-question-table thead,.anamnesis-question-table tbody{display:block!important;width:100%!important}.anamnesis-question-table thead tr,.anamnesis-question-table tbody tr{display:grid!important;grid-template-columns:minmax(0,2.35fr) minmax(0,1.2fr) 48px 76px 128px;width:100%!important}.anamnesis-question-table th,.anamnesis-question-table td{display:block!important;min-width:0!important;width:auto!important;white-space:normal!important;overflow-wrap:anywhere!important;word-break:break-word!important}.anamnesis-question-table .sort-column{text-align:center}.anamnesis-question-table .actions-column{white-space:nowrap!important}.anamnesis-question-table td{vertical-align:middle}@media(max-width:760px){.anamnesis-question-table thead tr,.anamnesis-question-table tbody tr{grid-template-columns:minmax(0,1fr) 70px 128px}.anamnesis-question-table .detail-column,.anamnesis-question-table .sort-column{display:none!important}.anamnesis-question-table .status-column{grid-column:2}.anamnesis-question-table .actions-column{grid-column:3}.anamnesis-question-table th,.anamnesis-question-table td{padding:12px 9px}}
</style>
<script>(()=>{const form=document.querySelector('.print-design-form'),canvas=form?.querySelector('.a4-designer'),hidden=form?.querySelector('[name="layout"]');if(!form||!canvas||!hidden)return;let layout={};try{layout=JSON.parse(hidden.value||'{}')}catch(_){layout={}};const defaults={header:{x:8,y:7},meta:{x:8,y:17},questions:{x:8,y:27},footer:{x:8,y:91}};layout={...defaults,...layout};const place=block=>{const key=block.dataset.designBlock,position=layout[key]||defaults[key];block.style.left=position.x+'%';block.style.top=position.y+'%'};canvas.querySelectorAll('.design-block').forEach(block=>{place(block);let start=null;block.addEventListener('pointerdown',event=>{event.preventDefault();block.setPointerCapture(event.pointerId);const rect=canvas.getBoundingClientRect(),position=layout[block.dataset.designBlock]||defaults[block.dataset.designBlock];start={x:event.clientX,y:event.clientY,left:position.x,top:position.y,rect};});block.addEventListener('pointermove',event=>{if(!start)return;const key=block.dataset.designBlock,maxX=100-(block.offsetWidth/start.rect.width*100),maxY=100-(block.offsetHeight/start.rect.height*100);layout[key]={x:Math.max(0,Math.min(maxX,start.left+(event.clientX-start.x)/start.rect.width*100)),y:Math.max(0,Math.min(maxY,start.top+(event.clientY-start.y)/start.rect.height*100))};place(block);});const finish=()=>{if(!start)return;start=null;hidden.value=JSON.stringify(layout)};block.addEventListener('pointerup',finish);block.addEventListener('pointercancel',finish);});})();</script>
<script>(()=>{const form=document.querySelector('.print-design-form'),canvas=form?.querySelector('.a4-designer'),hidden=form?.querySelector('[name="layout"]');if(!form||!canvas||!hidden)return;const snap=block=>{let layout={};try{layout=JSON.parse(hidden.value||'{}')}catch(_){}const key=block.dataset.designBlock,position=layout[key];if(!position)return;position.x=Math.round(position.x/5)*5;position.y=Math.round(position.y/5)*5;hidden.value=JSON.stringify(layout);block.style.left=position.x+'%';block.style.top=position.y+'%'};canvas.querySelectorAll('.design-block').forEach(block=>block.addEventListener('pointerup',()=>snap(block)));const preview=document.createElement('div');preview.className='print-preview-modal';preview.hidden=true;preview.innerHTML='<section class="print-preview-sheet"><button type="button" aria-label="Kapat">×</button><div class="print-preview-block header"></div><div class="print-preview-block meta">Hasta Ad Soyad · Tarih</div><div class="print-preview-block questions">Sorular<br><br>☐ Evet &nbsp; Açıklama alanı<br><br>☐ Evet &nbsp; Açıklama alanı</div><div class="print-preview-block footer">VOX İşitme Cihazları</div></section>';document.body.append(preview);const showPreview=()=>{let layout={};try{layout=JSON.parse(hidden.value||'{}')}catch(_){}const title=form.querySelector('[name="print_title"]').value,color=form.querySelector('[name="header_color"]').value;preview.querySelector('.header').textContent=title;preview.querySelectorAll('.print-preview-block').forEach(block=>{const key=block.classList.contains('header')?'header':block.classList.contains('meta')?'meta':block.classList.contains('questions')?'questions':'footer',position=layout[key]||{x:8,y:8};block.style.left=position.x+'%';block.style.top=position.y+'%';});preview.querySelector('.header').style.color=color;preview.hidden=false;};form.querySelector('.print-preview-button')?.addEventListener('click',showPreview);preview.addEventListener('click',event=>{if(event.target===preview||event.target.closest('button'))preview.hidden=true});})();</script>
<script>(()=>{const form=document.querySelector('.print-design-form'),canvas=form?.querySelector('.a4-designer'),hidden=form?.querySelector('[name="layout"]');if(!form||!canvas||!hidden)return;const grid=5,read=()=>{try{return JSON.parse(hidden.value||'{}')}catch(_){return {}}},write=value=>hidden.value=JSON.stringify(value);canvas.querySelectorAll('.design-block').forEach(block=>{let layout=read(),position=layout[block.dataset.designBlock]||{};if(position.width)block.style.width=position.width+'%';if(position.height)block.style.height=position.height+'%';const handle=document.createElement('span');handle.className='design-resize-handle';block.append(handle);let start=null;handle.addEventListener('pointerdown',event=>{event.preventDefault();event.stopPropagation();handle.setPointerCapture(event.pointerId);const rect=canvas.getBoundingClientRect(),blockRect=block.getBoundingClientRect();start={x:event.clientX,y:event.clientY,rect,width:blockRect.width/rect.width*100,height:blockRect.height/rect.height*100};});handle.addEventListener('pointermove',event=>{if(!start)return;const layout=read(),key=block.dataset.designBlock,position=layout[key]||{};const maxWidth=100-(position.x||0),maxHeight=100-(position.y||0);position.width=Math.max(grid,Math.min(maxWidth,Math.round((start.width+(event.clientX-start.x)/start.rect.width*100)/grid)*grid));position.height=Math.max(grid,Math.min(maxHeight,Math.round((start.height+(event.clientY-start.y)/start.rect.height*100)/grid)*grid));layout[key]=position;block.style.width=position.width+'%';block.style.height=position.height+'%';write(layout);});const stop=()=>{start=null};handle.addEventListener('pointerup',stop);handle.addEventListener('pointercancel',stop);});const questions=<?=json_encode(array_values(array_filter($rows, static fn(array $row): bool => (int)$row['active'] === 1)), JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;form.querySelector('.print-preview-button')?.addEventListener('click',()=>{const preview=document.querySelector('.print-preview-modal'),sheet=preview?.querySelector('.print-preview-sheet');if(!preview||!sheet)return;const layout=read();preview.querySelectorAll('.print-preview-block').forEach(block=>{const key=block.classList.contains('header')?'header':block.classList.contains('meta')?'meta':block.classList.contains('questions')?'questions':'footer',position=layout[key]||{};if(position.width)block.style.width=position.width+'%';if(position.height)block.style.height=position.height+'%';});const questionBlock=preview.querySelector('.questions');questionBlock.replaceChildren(...questions.map(question=>{const line=document.createElement('div');line.textContent='☐ ' + question.name + (question.detail_label ? ' — ' + question.detail_label : '');return line;}));});})();</script>
<script>(()=>{const form=document.querySelector('.print-design-form'),canvas=form?.querySelector('.a4-designer'),button=form?.querySelector('.print-preview-button');if(!form||!canvas||!button)return;button.addEventListener('click',()=>{const preview=document.querySelector('.print-preview-modal');if(!preview)return;const canvasRect=canvas.getBoundingClientRect();canvas.querySelectorAll('.design-block').forEach(source=>{const rect=source.getBoundingClientRect(),target=preview.querySelector('.'+source.dataset.designBlock);if(!target)return;target.style.setProperty('left',((rect.left-canvasRect.left)/canvasRect.width*100)+'%','important');target.style.setProperty('top',((rect.top-canvasRect.top)/canvasRect.height*100)+'%','important');target.style.setProperty('width',(rect.width/canvasRect.width*100)+'%','important');target.style.setProperty('height',(rect.height/canvasRect.height*100)+'%','important');});});})();</script>
<script>(()=>{const form=document.querySelector('.print-design-form'),button=form?.querySelector('.print-preview-button'),questions=<?=json_encode(array_values(array_filter($rows, static fn(array $row): bool => (int)$row['active'] === 1)), JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;if(!form||!button)return;button.addEventListener('click',()=>{const preview=document.querySelector('.print-preview-modal'),sheet=preview?.querySelector('.print-preview-sheet');if(!preview||!sheet)return;const value=name=>form.querySelector('[name="'+name+'"]').value,title=value('print_title'),color=value('header_color');sheet.replaceChildren();sheet.style.padding=value('page_margin')+'px';const close=document.createElement('button');close.type='button';close.textContent='×';sheet.append(close);const card=document.createElement('section');card.className='anamnesis-print-card';card.style.setProperty('--body-font',value('font_size')+'px');card.style.setProperty('--question-font',value('question_font_size')+'px');card.style.setProperty('--question-width',value('question_width')+'%');card.style.setProperty('--yes-width',value('yes_width')+'%');card.style.setProperty('--detail-width',value('detail_width')+'%');card.style.setProperty('--row-height',value('row_height')+'px');card.style.setProperty('--notes-height',value('notes_height')+'px');card.style.setProperty('--footer-height',value('footer_height')+'px');card.style.setProperty('--line-width',value('line_width')+'px');const heading=document.createElement('h1');heading.textContent=title;heading.style.color=color;card.append(heading);const table=document.createElement('table');const addRow=(cells,className='')=>{const row=document.createElement('tr');if(className)row.className=className;cells.forEach(cell=>{const td=document.createElement('td');td.textContent=cell.text||'';if(cell.colspan)td.colSpan=cell.colspan;if(cell.className)td.className=cell.className;row.append(td)});table.append(row)};addRow([{text:'AD SOYAD',colspan:2},{text:'TARİH'},{text:'',colspan:1}],'patient-row');addRow([{text:'ŞİKAYETİNİZ NEDİR ?',colspan:2},{text:'',colspan:2}]);addRow([{text:'KAÇ YILDIR ŞİKAYETİNİZ VAR',colspan:4}]);addRow([{text:'MESLEĞİNİZİ ÖĞRENEBİLİR MİYİZ',colspan:4}]);questions.forEach(question=>addRow([{text:question.name},{text:'□ EVET',className:'yes-cell'},{text:question.detail_label||''},{text:''}]));addRow([{text:'MEMLEKETİNİZ VE YAŞADIĞINIZ ŞEHİR',colspan:4}]);addRow([{text:'ODY OTOSKOPİK İNCELEME SONUCU',colspan:4}],'large-row');addRow([{text:'ODY GÖRÜŞ VE TAVSİYESİ',colspan:4}],'large-row');card.append(table);const footer=document.createElement('div');footer.className='print-card-footer';footer.textContent='VOX İşitme Cihazları';card.append(footer);sheet.append(card);preview.hidden=false;});})();</script>
<script>(()=>{const table=document.querySelector('.anamnesis-question-table');if(!table)return;const apply=row=>{row.style.setProperty('display','grid','important');row.style.setProperty('grid-template-columns','minmax(0, 2.35fr) minmax(0, 1.2fr) 48px 76px 128px','important');row.style.setProperty('width','100%','important');row.querySelectorAll('.question-column,.detail-column').forEach(cell=>{cell.style.setProperty('min-width','0','important');cell.style.setProperty('max-width','100%','important');cell.style.setProperty('white-space','normal','important');cell.style.setProperty('overflow-wrap','anywhere','important');cell.style.setProperty('word-break','break-word','important');});};table.querySelectorAll('thead tr,tbody tr').forEach(apply);})();</script>
<style>
  .print-preview-sheet:has(.anamnesis-print-card) { padding: 38px 60px 34px; box-sizing: border-box; }
  .anamnesis-print-card { height: 100%; box-sizing: border-box; border: var(--line-width, 1px) solid #111; color: #122542; font-family: Arial, sans-serif; font-size: var(--body-font, 8px); }
  .anamnesis-print-card h1 { margin: 0; padding: 12px 14px; border-bottom: calc(var(--line-width, 1px) * 2) solid #111; color: var(--print-title-color, #0d873d); font-family: Georgia, serif; font-size: 20px; line-height: 1; }
  .anamnesis-print-card table { width: 100%; border-collapse: collapse; table-layout: fixed; }
  .anamnesis-print-card td { height: var(--row-height, 27px); padding: 4px 9px; border-right: var(--line-width, 1px) solid #111; border-bottom: var(--line-width, 1px) solid #111; vertical-align: middle; overflow-wrap: anywhere; }
  .anamnesis-print-card td:last-child { border-right: 0; }
  .anamnesis-print-card tr td:nth-child(1) { width: var(--question-width, 46%); font-size: var(--question-font, 8px); }
  .anamnesis-print-card tr td:nth-child(2) { width: var(--yes-width, 12%); }
  .anamnesis-print-card tr td:nth-child(3) { width: var(--detail-width, 20%); }
  .anamnesis-print-card .yes-cell { text-align: center; font-weight: 700; }
  .anamnesis-print-card .patient-row td { height: 22px; font-size: 7px; }
  .anamnesis-print-card .large-row td { height: var(--notes-height, 37px); }
  .print-card-footer { height: var(--footer-height, 34px); display: flex; align-items: center; justify-content: center; font-weight: 700; }
  .print-settings-panel { display:grid; grid-template-columns:repeat(2,minmax(170px,1fr)); gap:14px; flex:1 1 390px; padding:18px; border:1px solid #e1e2e8; border-radius:8px; }
  .print-settings-panel h3 { grid-column:1/-1; margin:0; font-size:16px; }
  .print-settings-panel label input { min-width:0!important; width:100%; box-sizing:border-box; }
  .print-design-form .designer-help { flex-basis:100%; }
  @media(max-width:700px){.print-settings-panel{grid-template-columns:1fr;}.print-settings-panel h3{grid-column:auto;}}
</style>
<script>(()=>{const form=document.querySelector('.print-design-form'),button=form?.querySelector('.print-preview-button'),questions=<?=json_encode(array_values(array_filter($rows, static fn(array $row): bool => (int)$row['active'] === 1)), JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;if(!form||!button)return;const value=name=>form.querySelector('[name="'+name+'"]').value;button.addEventListener('click',()=>{let preview=document.querySelector('.print-preview-modal');if(!preview){preview=document.createElement('div');preview.className='print-preview-modal';preview.addEventListener('click',event=>{if(event.target===preview||event.target.closest('button'))preview.hidden=true});document.body.append(preview)}const sheet=document.createElement('section');sheet.className='print-preview-sheet';sheet.style.padding=value('page_margin')+'px';const close=document.createElement('button');close.type='button';close.setAttribute('aria-label','Kapat');close.textContent='×';sheet.append(close);const card=document.createElement('section');card.className='anamnesis-print-card';[['--body-font','font_size','px'],['--question-font','question_font_size','px'],['--question-width','question_width','%'],['--yes-width','yes_width','%'],['--detail-width','detail_width','%'],['--row-height','row_height','px'],['--notes-height','notes_height','px'],['--footer-height','footer_height','px'],['--line-width','line_width','px']].forEach(([css,name,unit])=>card.style.setProperty(css,value(name)+unit));const heading=document.createElement('h1');heading.textContent=value('print_title');heading.style.color=value('header_color');card.append(heading);const table=document.createElement('table');const row=(cells,kind='')=>{const tr=document.createElement('tr');tr.className=kind;cells.forEach(cell=>{const td=document.createElement('td');td.textContent=cell.text||'';td.colSpan=cell.span||1;td.className=cell.className||'';tr.append(td)});table.append(tr)};row([{text:'AD SOYAD',span:2},{text:'TARİH'},{text:''}],'patient-row');row([{text:'ŞİKAYETİNİZ NEDİR ?',span:2},{text:'',span:2}]);row([{text:'KAÇ YILDIR ŞİKAYETİNİZ VAR',span:4}]);row([{text:'MESLEĞİNİZİ ÖĞRENEBİLİR MİYİZ',span:4}]);questions.forEach(q=>row([{text:q.name},{text:'□ EVET',className:'yes-cell'},{text:q.detail_label||''},{text:''}]));row([{text:'MEMLEKETİNİZ VE YAŞADIĞINIZ ŞEHİR',span:4}]);row([{text:'ODY OTOSKOPİK İNCELEME SONUCU',span:4}],'large-row');row([{text:'ODY GÖRÜŞ VE TAVSİYESİ',span:4}],'large-row');card.append(table);const footer=document.createElement('div');footer.className='print-card-footer';footer.textContent='VOX İşitme Cihazları';card.append(footer);sheet.append(card);preview.replaceChildren(sheet);preview.hidden=false});})();</script>
<?php patient_footer(); ?>
