<?php
declare(strict_types=1);require __DIR__.'/config.php';require_admin();ensure_branch_schema();require __DIR__.'/patient-layout.php';$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'save';$id=(int)($_POST['id']??0);
 if($action==='toggle'&&$id){db()->prepare('UPDATE branches SET active=CASE WHEN active=1 THEN 0 ELSE 1 END WHERE id=?')->execute([$id]);$message='Şube durumu güncellendi.';}
 else{$name=trim((string)($_POST['name']??''));$code=mb_strtoupper(trim((string)($_POST['code']??'')));$phone=trim((string)($_POST['phone']??''));$address=trim((string)($_POST['address']??''));if($name==='')$error='Şube adı zorunludur.';else try{if($id){db()->prepare('UPDATE branches SET name=?,code=?,phone=?,address=? WHERE id=?')->execute([$name,$code,$phone,$address,$id]);$message='Şube güncellendi.';}else{db()->prepare('INSERT INTO branches(name,code,phone,address,active) VALUES(?,?,?,?,1)')->execute([$name,$code,$phone,$address]);$message='Şube eklendi.';}}catch(PDOException $e){$error='Bu şube adı daha önce kullanılmış.';}}
}
$edit=null;if(isset($_GET['edit'])){$s=db()->prepare('SELECT * FROM branches WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}$branches=db()->query('SELECT b.*,(SELECT COUNT(*) FROM patients p WHERE p.branch_id=b.id) patient_count,(SELECT COUNT(*) FROM users u WHERE u.branch_id=b.id) personnel_count FROM branches b ORDER BY b.active DESC,b.name')->fetchAll();patient_header('Ayarlar - Şubeler','settings');?>
<main class="patient-container branch-page"><nav class="settings-tabs"><a href="<?=url('admin.php')?>">Personel Yönetimi</a><a class="active" href="<?=url('branches.php')?>">Şubeler</a></nav><?php if($message):?><div class="notice success"><?=e($message)?></div><?php endif?><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif?>
<section class="branch-card"><header><h1><?=$edit?'Şubeyi Düzenle':'Yeni Şube'?></h1><p>Şube bilgilerini tanımlayın; personel ve hasta kayıtları bu şubelere bağlanır.</p></header><form method="post" class="branch-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>"><label>Şube Adı<input name="name" value="<?=e($edit['name']??'')?>" required></label><label>Şube Kodu<input name="code" value="<?=e($edit['code']??'')?>"></label><label>Telefon<input name="phone" value="<?=e($edit['phone']??'')?>"></label><label class="wide">Adres<textarea name="address"><?=e($edit['address']??'')?></textarea></label><div class="wide"><button>Kaydet</button><?php if($edit):?><a href="<?=url('branches.php')?>">İptal</a><?php endif?></div></form></section>
<section class="branch-card"><header><h2>Tanımlı Şubeler</h2></header><div class="table-scroll"><table><thead><tr><th>Şube</th><th>Kod</th><th>Telefon</th><th>Hasta</th><th>Personel</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody><?php foreach($branches as $b):?><tr><td><b><?=e($b['name'])?></b><small><?=e($b['address'])?></small></td><td><?=e($b['code'])?></td><td><?=e($b['phone'])?></td><td><?=(int)$b['patient_count']?></td><td><?=(int)$b['personnel_count']?></td><td><?=$b['active']?'Aktif':'Pasif'?></td><td><a class="edit" href="<?=url('branches.php?edit='.(int)$b['id'])?>">Düzenle</a><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=(int)$b['id']?>"><button class="toggle"><?=$b['active']?'Pasifleştir':'Aktifleştir'?></button></form></td></tr><?php endforeach?></tbody></table></div></section></main>
<style>.branch-page{max-width:1180px;margin:auto;padding:28px 20px}.settings-tabs{display:flex;gap:8px;margin-bottom:20px}.settings-tabs a{padding:11px 16px;border-radius:7px;text-decoration:none;color:#16883d;background:#e8f7ed;font-weight:700}.settings-tabs a.active{background:#19a94b;color:#fff}.branch-card{background:var(--card,#fff);border:1px solid var(--line,#ddd);border-radius:9px;margin-bottom:22px;overflow:hidden}.branch-card>header{padding:20px 24px;border-bottom:1px solid var(--line,#ddd)}.branch-card h1,.branch-card h2{margin:0 0 5px}.branch-card p{margin:0;color:var(--muted)}.branch-form{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;padding:24px}.branch-form label{display:flex;flex-direction:column;gap:7px}.branch-form input,.branch-form textarea{border:1px solid #d4d5dd;border-radius:6px;padding:10px;background:transparent;color:inherit}.branch-form .wide{grid-column:1/-1}.branch-form button,.edit,.toggle{display:inline-flex;border:0;border-radius:6px;padding:9px 13px;background:#19a94b;color:#fff;text-decoration:none;font-weight:700}.table-scroll{overflow:auto}.branch-card table{width:100%;min-width:800px;border-collapse:collapse}.branch-card th,.branch-card td{padding:13px 18px;text-align:left;border-bottom:1px solid var(--line,#ddd)}.branch-card td small{display:block;color:var(--muted)}.branch-card td form{display:inline}.toggle{background:#78808d}.notice{padding:12px 15px;margin-bottom:16px;border-radius:7px}.notice.success{background:#dff5e6;color:#147238}.notice.error{background:#ffe2e2;color:#9b2020}[data-theme=dark] .branch-card{background:#2f3349;color:#fff}@media(max-width:700px){.branch-form{grid-template-columns:1fr}.branch-form .wide{grid-column:auto}}</style><?php patient_footer();?>
