INSERT IGNORE INTO item_definitions (category,name,sort_order) VALUES
('Bebek ve Çocuk','Bebek Önlüğü',100),
('Bebek ve Çocuk','Bebek yağı',101),
('Bebek ve Çocuk','Bebek Yatağı',102),
('Bebek ve Çocuk','Bebek yiyecekleri',103),
('Bebek ve Çocuk','Biberon',104),
('Bebek ve Çocuk','Çocuk Suluk',105),
('Bebek ve Çocuk','Deniz Oyuncakları',106),
('Bebek ve Çocuk','Diğer Bebek ve Çocuk Malzemeleri',107),
('Bebek ve Çocuk','Emzik',108),
('Bebek ve Çocuk','Mama Masası',109),
('Bebek ve Çocuk','Peluş Kulaklık',110),
('Bebek ve Çocuk','Peluş Oyuncak',111),
('Bebek ve Çocuk','Plastik Oyuncak',112),
('Bebek ve Çocuk','Puset',113),
('Diğer','Boya Kartelası',114),
('Diğer','Diğer',115),
('Diğer','Kumaş Kartelası',116),
('Elektronik Eşya','Adaptör',117),
('Elektronik Eşya','Airpod kutusu',118),
('Elektronik Eşya','Airpods',119),
('Elektronik Eşya','Airtag',120),
('Elektronik Eşya','Akıllı Saat',121),
('Elektronik Eşya','Bluetooth-Kablosuz Kulaklık',122),
('Elektronik Eşya','Coin',123),
('Elektronik Eşya','Diğer Elektronik Eşya',124),
('Elektronik Eşya','Dizüstü Bilgisayar',125),
('Elektronik Eşya','Dokunmatik Tablet Kalemi',126),
('Elektronik Eşya','DVD Çalar',127),
('Elektronik Eşya','E-Kitap',128),
('Elektronik Eşya','El Vantilatörü',129),
('Elektronik Eşya','Elektronik Sigara',130),
('Elektronik Eşya','Fare (mouse)',131),
('Elektronik Eşya','Fitness Aleti',132),
('Elektronik Eşya','Foto/Kamera Lens',133),
('Elektronik Eşya','Fotoğraf Makinası-Kamera',134),
('Elektronik Eşya','Giyilebilir Cihazlar',135),
('Elektronik Eşya','Harici Disk-USB-Flash Bellek',136),
('Elektronik Eşya','Hesap Makinası',137),
('Elektronik Eşya','Hoparlör',138),
('Elektronik Eşya','Isıtıcı',139),
('Elektronik Eşya','Kablo',140),
('Elektronik Eşya','Klavye',141),
('Elektronik Eşya','Kulakiçi Kulaklık',142),
('Elektronik Eşya','Kulaklık',143),
('Elektronik Eşya','Kulaklık Kutusu',144),
('Elektronik Eşya','Küçük Elektronik Ev Cihazları',145),
('Elektronik Eşya','Mikrofon',146),
('Elektronik Eşya','Mobil Modem',147),
('Elektronik Eşya','Monitör',148),
('Elektronik Eşya','MP3-MP4 Çalar',149),
('Elektronik Eşya','Navigasyon/GPS Cihazı',150),
('Elektronik Eşya','Oyun Cihaz ve Aksesuarları',151),
('Elektronik Eşya','Oyun Konsolu',152),
('Elektronik Eşya','Powerbank',153),
('Elektronik Eşya','Projektör',154),
('Elektronik Eşya','Sabit Modem',155),
('Elektronik Eşya','Sim kart',156),
('Elektronik Eşya','Spor Takip Aleti',157),
('Elektronik Eşya','Su Isıtıcısı',158),
('Elektronik Eşya','Şarj Cihazı',159),
('Elektronik Eşya','Şarj Kablosu',160),
('Elektronik Eşya','Tablet',161),
('Elektronik Eşya','Telefon',162),
('Elektronik Eşya','Telefon - Sabit',163),
('Elektronik Eşya','Televizyon',164),
('Elektronik Eşya','Telsiz',165),
('Elektronik Eşya','USB / USB-C kablo',166),
('Elektronik Eşya','Uzaktan Kumanda',167),
('Elektronik Eşya','Yazıcı',168),
('Ev Araç Eşyaları','Alet Çantası',169),
('Ev Araç Eşyaları','Anahtar',170);
