<?php
require __DIR__ . '/config.php'; require_login(); require __DIR__ . '/patient-layout.php';
$total=(int)db()->query('SELECT COUNT(*) FROM patients')->fetchColumn();
$approved=(int)db()->query('SELECT COUNT(*) FROM patients WHERE approval=1')->fetchColumn();
$considering=(int)db()->query('SELECT COUNT(*) FROM patients WHERE considering=1')->fetchColumn();
$rejected=(int)db()->query('SELECT COUNT(*) FROM patients WHERE rejected=1')->fetchColumn();
$pdo = db();
$yearExpression = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME) === 'sqlite' ? 'substr(record_date,1,4)' : 'YEAR(record_date)';
$yearlyRows = $pdo->query("SELECT {$yearExpression} AS year_key, COUNT(*) AS total FROM patients WHERE record_date IS NOT NULL AND record_date <> '' GROUP BY {$yearExpression} ORDER BY year_key")->fetchAll();
$yearlyChart = array_map(static fn(array $row): array => ['label' => (string)$row['year_key'], 'total' => (int)$row['total']], $yearlyRows);
$yearlySuccessRows = $pdo->query("SELECT {$yearExpression} AS year_key, COUNT(*) AS total, COALESCE(SUM(CASE WHEN approval=1 THEN 1 ELSE 0 END),0) AS approved FROM patients WHERE record_date IS NOT NULL AND record_date <> '' GROUP BY {$yearExpression} ORDER BY year_key")->fetchAll();
$yearlySuccess = array_map(static fn(array $row): array => ['year'=>(string)$row['year_key'], 'total'=>(int)$row['total'], 'approved'=>(int)$row['approved'], 'rate'=>(int)$row['total'] ? round(((int)$row['approved'] / (int)$row['total']) * 100, 1) : 0], $yearlySuccessRows);
if (!$yearlyChart) $yearlyChart = [['label' => date('Y'), 'total' => 0]];
$yearlyMax = max(1, ...array_column($yearlyChart, 'total'));
$availableYears = array_map(static fn(array $year): int => (int)$year['label'], $yearlyChart);
$selectedChartYear = (int)($_GET['chart_year'] ?? end($availableYears));
if (!in_array($selectedChartYear, $availableYears, true)) $selectedChartYear = (int)end($availableYears);
$monthExpression = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME) === 'sqlite' ? 'substr(record_date,6,2)' : "DATE_FORMAT(record_date,'%m')";
$monthlyStatement = $pdo->prepare("SELECT {$monthExpression} AS month_key, COUNT(*) AS total FROM patients WHERE record_date LIKE ? GROUP BY {$monthExpression}");
$monthlyStatement->execute([$selectedChartYear . '-%']);
$selectedYearTotals = [];
foreach ($monthlyStatement->fetchAll() as $monthRow) $selectedYearTotals[(int)$monthRow['month_key']] = (int)$monthRow['total'];
$monthLabels = ['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara'];
$selectedYearMonths = [];
for ($month = 1; $month <= 12; $month++) $selectedYearMonths[] = ['label' => $monthLabels[$month - 1], 'total' => $selectedYearTotals[$month] ?? 0];
$selectedYearMax = max(1, ...array_column($selectedYearMonths, 'total'));
$yearSuccessStatement = $pdo->prepare('SELECT COUNT(*) AS total, COALESCE(SUM(CASE WHEN approval=1 THEN 1 ELSE 0 END),0) AS approved FROM patients WHERE record_date LIKE ?');
$yearSuccessStatement->execute([$selectedChartYear . '-%']);
$selectedYearSuccess = $yearSuccessStatement->fetch() ?: ['total'=>0,'approved'=>0];
$totalSuccessRate = $total ? round(($approved / $total) * 100, 1) : 0;
$yearSuccessRate = (int)$selectedYearSuccess['total'] ? round(((int)$selectedYearSuccess['approved'] / (int)$selectedYearSuccess['total']) * 100, 1) : 0;
$comparisonRows = $pdo->query("SELECT {$yearExpression} AS year_key, {$monthExpression} AS month_key, COUNT(*) AS total FROM patients WHERE record_date IS NOT NULL AND record_date <> '' GROUP BY {$yearExpression}, {$monthExpression}")->fetchAll();
$monthYearTotals = [];
foreach ($comparisonRows as $comparisonRow) $monthYearTotals[(int)$comparisonRow['month_key']][(int)$comparisonRow['year_key']] = (int)$comparisonRow['total'];
$comparisonMax = 1;
foreach ($monthYearTotals as $monthTotals) foreach ($monthTotals as $monthTotal) $comparisonMax = max($comparisonMax, $monthTotal);
$recent=db()->query('SELECT patients.*, NULL AS service_location FROM patients ORDER BY import_order,id LIMIT 10')->fetchAll();
$employeeAnalysisYear = '2026';
$activeEmployees = [];
try {$stmt=$pdo->prepare("SELECT full_name FROM employees WHERE start_date<=? AND (end_date IS NULL OR end_date='' OR end_date>=?)");$stmt->execute([$employeeAnalysisYear.'-12-31',$employeeAnalysisYear.'-01-01']);$activeEmployees=array_fill_keys(array_map(static fn(array $x):string=>mb_strtolower(trim((string)$x['full_name']),'UTF-8'),$stmt->fetchAll()),true);}catch(Throwable $e){}
$employeePerformance=[];
if($activeEmployees){$stmt=$pdo->prepare("SELECT contact_person,service_name,appointment_status FROM patient_services WHERE COALESCE(contact_person,'')<>'' AND service_date LIKE ?");$stmt->execute([$employeeAnalysisYear.'-%']);foreach($stmt as $service)foreach(preg_split('/\s*,\s*/u',(string)$service['contact_person'],-1,PREG_SPLIT_NO_EMPTY)?:[] as $name){$name=trim($name);$key=mb_strtolower($name,'UTF-8');if($name===''||!isset($activeEmployees[$key]))continue;$employeePerformance[$key]??=['name'=>$name,'total'=>0,'completed'=>0,'sales'=>0];$employeePerformance[$key]['total']++;if((string)$service['appointment_status']==='Tamamlandı')$employeePerformance[$key]['completed']++;if((string)$service['service_name']==='Satış')$employeePerformance[$key]['sales']++;}}
$employeePerformance=array_values($employeePerformance);usort($employeePerformance,static fn(array $a,array $b):int=>$b['total']<=>$a['total']);
$heroYear = '2026';
$heroStatement = $pdo->prepare("SELECT COUNT(*) AS total,COALESCE(SUM(CASE WHEN approval=1 THEN 1 ELSE 0 END),0) AS approved,COALESCE(SUM(CASE WHEN considering=1 THEN 1 ELSE 0 END),0) AS considering,COALESCE(SUM(CASE WHEN rejected=1 THEN 1 ELSE 0 END),0) AS rejected FROM patients WHERE record_date LIKE ?");
$heroStatement->execute([$heroYear . '-%']);
$heroMetrics = $heroStatement->fetch() ?: ['total'=>0,'approved'=>0,'considering'=>0,'rejected'=>0];
$topHearingDevices = $pdo->query("SELECT s.stock_code,s.stock_name,s.brand,s.model,SUM(m.quantity) AS quantity FROM stock_movements m INNER JOIN stock_cards s ON s.id=m.stock_id WHERE m.movement_type='Çıkış' AND s.stock_type='İşitme Cihazı' GROUP BY s.id,s.stock_code,s.stock_name,s.brand,s.model ORDER BY quantity DESC,s.stock_name LIMIT 4")->fetchAll();
patient_header('Ana Sayfa','home');
?>
<script>document.addEventListener('DOMContentLoaded',()=>{const metrics=<?=json_encode($heroMetrics,JSON_UNESCAPED_UNICODE)?>,values=[metrics.total,metrics.approved,metrics.considering,metrics.rejected];document.querySelectorAll('.stats .stat').forEach((card,index)=>{const label=card.querySelector('span'),value=card.querySelector('strong');if(label)label.textContent='2026 '+['Toplam Kayıt','Onaylanan','Düşünecek','Reddedilen'][index];if(value)value.textContent=values[index]??0;});});</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const actual=<?=json_encode(['patients'=>(int)$heroMetrics['total'],'sales'=>(int)$heroMetrics['approved']],JSON_UNESCAPED_UNICODE)?>,targets={patients:250,sales:130},grid=document.querySelector('.sales-success-grid'),card=(title,actualValue,targetValue,label)=>{const rate=Math.min(100,Math.round(actualValue/targetValue*100));return `<article class="card sales-success-card"><div class="success-donut" style="--rate:${rate}"><b>${rate}%</b></div><div class="success-detail"><h3>${title}</h3><p>2026 başlangıç hedefi: ${targetValue}</p><strong>${actualValue} / ${targetValue}</strong><span>${label} · Kalan: ${Math.max(0,targetValue-actualValue)}</span></div></article>`;};if(grid)grid.innerHTML=card('2026 Hasta Hedefi',actual.patients,targets.patients,'Gerçekleşen hasta kaydı')+card('2026 Satış Hedefi',actual.sales,targets.sales,'Gerçekleşen satış');});</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const products=<?=json_encode($topHearingDevices,JSON_UNESCAPED_UNICODE)?>,grid=document.querySelector('.year-sales-grid'),escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));if(!grid)return;grid.setAttribute('aria-label','En çok satılan işitme cihazları');grid.innerHTML=products.map((product,index)=>`<article class="card sales-success-card best-device-card"><span class="best-device-rank">${index+1}</span><div class="success-detail"><h3>${escape(product.brand||'')} ${escape(product.model||product.stock_name)}</h3><p>${escape(product.stock_code)} — ${escape(product.stock_name)}</p><strong>${product.quantity} adet</strong><span>Satılan işitme cihazı</span></div></article>`).join('')||'<article class="card sales-success-card"><div class="success-detail"><h3>Satış verisi bulunmuyor</h3><p>Henüz işitme cihazı çıkışı kaydedilmemiş.</p></div></article>';});</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const metrics=<?=json_encode($heroMetrics,JSON_UNESCAPED_UNICODE)?>,hero=document.querySelector('.dashboard-hero');if(!hero)return;hero.querySelector('h2').textContent='Vox İşitme ERP — 2026';hero.querySelector('p').textContent='2026 yılı hasta süreçlerini tek ekrandan takip edin.';hero.querySelector('.hero-metrics').innerHTML=`<div><b>${metrics.total}</b> Toplam kayıt</div><div><b>${metrics.approved}</b> Onaylanan</div><div><b>${metrics.considering}</b> Düşünecek</div><div><b>${metrics.rejected}</b> Reddedilen</div>`;});</script>
<script>document.addEventListener('DOMContentLoaded',()=>{const staff=<?=json_encode($employeePerformance,JSON_UNESCAPED_UNICODE)?>,e=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const cards=[...document.querySelectorAll('.monthly-chart-card')],max=Math.max(1,...staff.map(x=>x.total));if(cards[0]){cards[0].querySelector('h2').textContent='2026 Aktif Çalışan İş Yükü';cards[0].querySelector('p').textContent='2026 hizmet kartlarına göre';cards[0].querySelector('.yearly-chart').innerHTML=staff.map(x=>`<div class="month-bar"><span class="month-value">${x.total}</span><div class="month-track"><span style="height:${Math.max(2,x.total/max*100)}%"></span></div><span class="month-label">${e(x.name)}</span></div>`).join('');}if(cards[1]){cards[1].querySelector('h2').textContent='2026 Tamamlanan İşlemler';cards[1].querySelector('p').textContent='Aktif çalışan bazında';cards[1].querySelector('form')?.remove();cards[1].querySelector('.monthly-chart').innerHTML=staff.map(x=>`<div class="month-bar"><span class="month-value">${x.completed}</span><div class="month-track"><span style="height:${Math.max(2,x.total?x.completed/x.total*100:2)}%"></span></div><span class="month-label">${e(x.name)}</span></div>`).join('');}if(cards[2]){cards[2].querySelector('h2').textContent='2026 Satış Performansı';cards[2].querySelector('p').textContent='Aktif çalışan bazında';cards[2].querySelector('.chart-legend')?.remove();cards[2].querySelector('.year-month-chart').innerHTML=staff.map(x=>`<div class="compare-month"><div class="compare-bars"><span class="compare-bar compare-0" style="height:${Math.max(2,x.sales/max*100)}%"></span></div><span>${e(x.name)}</span></div>`).join('');}});</script>
<style>
.best-device-card{position:relative;min-height:122px;padding-left:68px!important}.best-device-rank{position:absolute;top:22px;left:22px;display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:#e7f8ec;color:#159447;font-size:16px;font-weight:800}.best-device-card .success-detail h3{font-size:16px}.best-device-card .success-detail strong{font-size:22px;color:#159447}
.dashboard .list-card{display:none}
.dashboard{padding-top:30px!important}
.dashboard-overview{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(270px,.7fr) minmax(270px,.7fr);gap:22px;margin-bottom:22px}
.dashboard-hero{position:relative;min-height:250px;padding:28px 30px;overflow:hidden;border-radius:10px;background:linear-gradient(135deg,#17883d 0%,#20a447 54%,#67c936 100%);color:#fff;box-shadow:0 10px 24px rgba(32,164,71,.25)}
.dashboard-hero:before,.dashboard-hero:after{content:"";position:absolute;border:18px solid rgba(255,255,255,.14);border-radius:50%;width:190px;height:190px;right:-52px;bottom:-72px}.dashboard-hero:after{width:116px;height:116px;right:54px;bottom:38px;border-width:12px;border-color:rgba(255,255,255,.12)}
.dashboard-hero h2{position:relative;margin:0 0 6px;color:#fff;font-size:22px}.dashboard-hero p{position:relative;margin:0;color:rgba(255,255,255,.82)}
.hero-metrics{position:relative;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:42px;max-width:350px}.hero-metrics div{display:flex;align-items:center;gap:9px;font-size:14px;font-weight:700}.hero-metrics b{display:inline-grid;place-items:center;min-width:49px;height:35px;border-radius:7px;background:rgba(20,77,39,.32);font-size:17px}
.dashboard-mini{min-height:250px;padding:26px 24px}.dashboard-mini h3{margin:0 0 6px;font-size:18px}.dashboard-mini p{margin:0;color:var(--muted)}.dashboard-mini .mini-number{display:block;margin:22px 0 7px;font-size:36px;font-weight:700}.mini-line{height:92px;margin:10px -24px 0;background:linear-gradient(180deg,rgba(32,164,71,.22),rgba(32,164,71,0));clip-path:polygon(0 76%,18% 82%,36% 52%,55% 64%,75% 18%,100% 39%,100% 100%,0 100%)}.status-head{display:flex;justify-content:space-between;color:var(--muted)}.status-head b{color:#20a447}.status-number{font-size:32px;font-weight:700;margin:5px 0 20px}.status-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;align-items:center}.status-item{display:flex;flex-direction:column;gap:5px}.status-item span{color:var(--muted)}.status-item b{font-size:20px}.status-progress{height:10px;border-radius:10px;overflow:hidden;background:#e7f6eb;margin-top:auto}.status-progress i{display:block;height:100%;background:linear-gradient(90deg,#20a447,#66c936);border-radius:inherit}
.dashboard .stats{margin-bottom:22px}.dashboard .monthly-chart-card{border:1px solid rgba(34,35,58,.04)}
.sales-success-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px;margin-bottom:22px}.year-sales-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(275px,1fr));gap:18px;margin-bottom:22px}.sales-success-card{display:flex;align-items:center;gap:24px;padding:22px 26px}.sales-success-card h3{margin:0 0 7px;font-size:18px}.sales-success-card p{margin:0;color:var(--muted)}.success-donut{--rate:0;display:grid;place-items:center;flex:0 0 132px;width:132px;height:132px;border-radius:50%;background:conic-gradient(#20a447 calc(var(--rate) * 1%),#ebedf1 0);position:relative}.success-donut:after{content:"";position:absolute;inset:15px;border-radius:50%;background:var(--card)}.success-donut b{position:relative;z-index:1;font-size:25px;color:#20a447}.success-detail{display:grid;gap:5px}.success-detail strong{font-size:24px}.success-detail span{color:var(--muted)}.year-sales-grid .sales-success-card{padding:18px}.year-sales-grid .success-donut{flex-basis:94px;width:94px;height:94px}.year-sales-grid .success-donut:after{inset:12px}.year-sales-grid .success-donut b{font-size:18px}.year-sales-grid .success-detail strong{font-size:19px}
@media(max-width:1180px){.dashboard-overview{grid-template-columns:repeat(2,minmax(0,1fr))}.dashboard-hero{grid-column:span 2}}@media(max-width:700px){.dashboard-overview,.sales-success-grid{grid-template-columns:1fr}.dashboard-hero{grid-column:auto}.dashboard-hero,.dashboard-mini{min-height:220px}.hero-metrics{margin-top:26px}.sales-success-card{padding:20px}.success-donut{flex-basis:112px;width:112px;height:112px}}
</style>
<main class="patient-container dashboard">
  <section class="page-head"><div><h1>Hasta Kayıtları</h1><p>Hasta bilgilerini kaydedin, takip edin ve süreçleri yönetin.</p></div></section>
  <section class="dashboard-overview">
    <article class="dashboard-hero"><h2>Vox İşitme ERP</h2><p>Hasta süreçlerini tek ekrandan takip edin.</p><div class="hero-metrics"><div><b><?=$total?></b> Toplam kayıt</div><div><b><?=$approved?></b> Onaylanan</div><div><b><?=$considering?></b> Düşünecek</div><div><b><?=$rejected?></b> Reddedilen</div></div></article>
    <article class="card dashboard-mini"><h3>Seçilen Yıl</h3><p><?=$selectedChartYear?> yılı kayıt görünümü</p><span class="mini-number"><?=array_sum(array_column($selectedYearMonths,'total'))?></span><span>Hasta kaydı</span><div class="mini-line"></div></article>
    <article class="card dashboard-mini"><div class="status-head"><span>Onay Durumu</span><b><?= $total ? round(($approved / $total) * 100) : 0 ?>%</b></div><div class="status-number"><?=$approved?></div><div class="status-grid"><div class="status-item"><span>Düşünecek</span><b><?=$considering?></b></div><div class="status-item"><span>Reddedilen</span><b><?=$rejected?></b></div></div><div class="status-progress"><i style="width:<?= $total ? round(($approved / $total) * 100) : 0 ?>%"></i></div></article>
  </section>
  <section class="sales-success-grid" aria-label="Satış başarı oranları">
    <article class="card sales-success-card"><div class="success-donut" style="--rate:<?=$totalSuccessRate?>"><b><?=$totalSuccessRate?>%</b></div><div class="success-detail"><h3>Toplam Satış Başarı Oranı</h3><p>Tüm hasta kayıtlarında onaylanan satışlar</p><strong><?=$approved?> / <?=$total?></strong><span>Onaylanan / toplam kayıt</span></div></article>
    <article class="card sales-success-card"><div class="success-donut" style="--rate:<?=$yearSuccessRate?>"><b><?=$yearSuccessRate?>%</b></div><div class="success-detail"><h3><?=$selectedChartYear?> Satış Başarı Oranı</h3><p>Seçilen yılın onaylanan satışları</p><strong><?=(int)$selectedYearSuccess['approved']?> / <?=(int)$selectedYearSuccess['total']?></strong><span>Onaylanan / toplam kayıt</span></div></article>
  </section>
  <section class="year-sales-grid" aria-label="Yıl bazlı satış başarı oranları">
    <?php foreach($yearlySuccess as $yearSuccess): ?><article class="card sales-success-card"><div class="success-donut" style="--rate:<?=$yearSuccess['rate']?>"><b><?=$yearSuccess['rate']?>%</b></div><div class="success-detail"><h3><?=$yearSuccess['year']?> Başarı Oranı</h3><strong><?=$yearSuccess['approved']?> / <?=$yearSuccess['total']?></strong><span>Onaylanan / toplam kayıt</span></div></article><?php endforeach; ?>
  </section>
  <section class="stats"><article class="card stat purple"><span>Toplam Kayıt</span><strong><?=$total?></strong></article><article class="card stat cyan"><span>Onaylanan</span><strong><?=$approved?></strong></article><article class="card stat orange"><span>Düşünecek</span><strong><?=$considering?></strong></article><article class="card stat green"><span>Reddedilen</span><strong><?=$rejected?></strong></article></section>
  <section class="card monthly-chart-card"><header><div><h2>Yıllık Hasta Dağılımı</h2><p>Hasta kayıt tarihine göre yıllara göre toplam kayıtlar</p></div><span class="chart-total"><?=$total?> toplam kayıt</span></header><div class="monthly-chart yearly-chart" role="img" aria-label="Yıllık hasta dağılım grafiği"><?php foreach($yearlyChart as $year):?><div class="month-bar"><span class="month-value"><?=(int)$year['total']?></span><div class="month-track"><span style="height:<?=max(2, ($year['total'] / $yearlyMax) * 100)?>%"></span></div><span class="month-label"><?=e($year['label'])?></span></div><?php endforeach?></div></section>
  <section class="card monthly-chart-card"><header><div><h2>Aylık Hasta Dağılımı</h2><p>Seçilen yılın aylara göre hasta kayıtları</p></div><form class="chart-year-form" method="get"><label for="chart_year">Yıl</label><select id="chart_year" name="chart_year" onchange="this.form.submit()"><?php foreach($availableYears as $year):?><option value="<?=$year?>" <?=$year===$selectedChartYear?'selected':''?>><?=$year?></option><?php endforeach?></select></form></header><div class="monthly-chart" role="img" aria-label="<?=$selectedChartYear?> yılı aylık hasta dağılım grafiği"><?php foreach($selectedYearMonths as $month):?><div class="month-bar"><span class="month-value"><?=(int)$month['total']?></span><div class="month-track"><span style="height:<?=max(2, ($month['total'] / $selectedYearMax) * 100)?>%"></span></div><span class="month-label"><?=e($month['label'])?></span></div><?php endforeach?></div></section>
  <section class="card monthly-chart-card"><header><div><h2>Yıllara Göre Aylık Karşılaştırma</h2><p>Aynı ayların yıllara göre hasta kayıt sayıları</p></div><div class="chart-legend"><?php foreach($availableYears as $yearIndex=>$year):?><span class="legend-year legend-<?=$yearIndex?>"><i></i><?=$year?></span><?php endforeach?></div></header><div class="year-month-chart" role="img" aria-label="Yıllara göre aylık hasta karşılaştırma grafiği"><?php for($month=1;$month<=12;$month++):?><div class="compare-month"><div class="compare-bars"><?php foreach($availableYears as $yearIndex=>$year):$monthTotal=$monthYearTotals[$month][$year]??0;?><span class="compare-bar compare-<?=$yearIndex?>" title="<?=$year?> <?=e($monthLabels[$month-1])?>: <?=$monthTotal?> hasta" style="height:<?=max(2, ($monthTotal / $comparisonMax) * 100)?>%"></span><?php endforeach?></div><span><?=e($monthLabels[$month-1])?></span></div><?php endfor?></div></section>
  <section class="card list-card"><div class="quick-filter"><input placeholder="Ad soyad, T.C. kimlik no veya telefon ile arayın"><a class="button" href="<?=url('patients.php')?>">Ara</a></div><div class="table-wrap"><table class="patient-table"><thead><tr><th>No</th><th>Tarih</th><th>Ad Soyad</th><th>T.C. Kimlik No</th><th>Telefon 1</th><th>Telefon 2</th><th>Doğum Tarihi</th><th>Adres</th><th>Sosyal Güvence</th><th>Rapor</th><th>Şube / Hizmet</th><th>Sonuç</th><th>Eylemler</th></tr></thead><tbody>
  <?php foreach($recent as $r):?><tr><td><?=(int)$r['import_order']?></td><td><?=e($r['record_date'])?></td><td><b><?=e($r['full_name'])?></b></td><td><?=e($r['national_id'])?></td><td><?=e($r['phone_primary'])?></td><td><?=e($r['phone_secondary'])?></td><td><?=e($r['birth_date'])?></td><td class="address"><?=e($r['address'])?></td><td><?=e($r['social_security'])?></td><td><?=e($r['report_info'])?></td><td><?=e($r['service_location'])?><br><small><?=e($r['service_type'])?></small></td><td><?=$r['approval']?'Onay':($r['considering']?'Düşünecek':($r['rejected']?'Ret':'—'))?></td><td><div class="actions"><a class="edit" href="<?=url('patient-form.php?id='.(int)$r['id'])?>">✎</a><form method="post" action="<?=url('patient-delete.php')?>" onsubmit="return confirm('Bu hasta kaydı silinsin mi?')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><button class="delete">×</button></form></div></td></tr><?php endforeach?>
  </tbody></table></div><div class="list-footer"><a href="<?=url('patients.php')?>">Tüm hasta kayıtlarını görüntüle →</a></div></section>
</main>
<?php patient_footer();
