<?php
declare(strict_types=1);
require __DIR__.'/config.php';require_login();require __DIR__.'/patient-layout.php';$pdo=db();
$filterText=trim((string)($_GET['q']??''));$filterAccountId=filter_input(INPUT_GET,'account_id',FILTER_VALIDATE_INT)?:0;$filterDateStart=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['date_start']??''))?(string)$_GET['date_start']:'';$filterDateEnd=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['date_end']??''))?(string)$_GET['date_end']:'';$dateSort=(($_GET['date_sort']??'desc')==='asc')?'asc':'desc';
$where=['TRIM(COALESCE(m.invoice_no,""))<>""'];$params=[];
if($filterAccountId>0){$where[]='m.current_account_id=?';$params[]=$filterAccountId;}if($filterDateStart!==''){$where[]='m.movement_date>=?';$params[]=$filterDateStart;}if($filterDateEnd!==''){$where[]='m.movement_date<=?';$params[]=$filterDateEnd;}
if($filterText!==''){$like='%'.$filterText.'%';$dateLike=$like;if(preg_match('/^(\d{2})\.(\d{2})\.(\d{4})$/',$filterText,$dateParts)&&checkdate((int)$dateParts[2],(int)$dateParts[1],(int)$dateParts[3]))$dateLike='%'.$dateParts[3].'-'.$dateParts[2].'-'.$dateParts[1].'%';$where[]='(COALESCE(m.invoice_no,"") LIKE ? OR COALESCE(c.code,"") LIKE ? OR COALESCE(c.title,"") LIKE ? OR COALESCE(c.short_name,"") LIKE ? OR m.movement_date LIKE ? OR EXISTS (SELECT 1 FROM stock_movements sm INNER JOIN stock_cards sc ON sc.id=sm.stock_id WHERE LOWER(TRIM(sm.invoice_no))=LOWER(TRIM(m.invoice_no)) AND sm.movement_type=m.movement_type AND (sc.stock_code LIKE ? OR sc.stock_name LIKE ?)))';array_push($params,$like,$like,$like,$like,$dateLike,$like,$like);}
$sql='SELECT MAX(m.invoice_no) invoice_no,m.movement_type,MIN(m.movement_date) movement_date,MAX(c.code) account_code,MAX(COALESCE(c.short_name,c.title)) account_name,COUNT(*) line_count,SUM(COALESCE(m.purchase_price,0)+ROUND(COALESCE(m.purchase_price,0)*COALESCE(m.vat_rate,0)/100,2)) total FROM stock_movements m LEFT JOIN current_accounts c ON c.id=m.current_account_id WHERE '.implode(' AND ',$where).' GROUP BY LOWER(TRIM(m.invoice_no)),m.movement_type ORDER BY MIN(m.movement_date) '.strtoupper($dateSort).',MAX(m.id) '.strtoupper($dateSort);$statement=$pdo->prepare($sql);$statement->execute($params);$invoices=$statement->fetchAll();
$sortQuery=http_build_query(['q'=>$filterText?:null,'account_id'=>$filterAccountId?:null,'date_start'=>$filterDateStart?:null,'date_end'=>$filterDateEnd?:null,'date_sort'=>$dateSort==='asc'?'desc':'asc']);
$accounts=$pdo->query("SELECT id,title,short_name FROM current_accounts WHERE account_type IN ('supplier','both') ORDER BY COALESCE(short_name,title)")->fetchAll();$selectedAccountName='';foreach($accounts as $account)if((int)$account['id']===$filterAccountId){$selectedAccountName=(string)($account['short_name']?:$account['title']);break;}
patient_header('Fatura Listesi','stock');?>
<main class="patient-container inv-list"><section><header><div><h1>Fatura Listesi</h1><p>Stok giriş ve çıkış faturaları.</p></div><a href="<?=e(url('invoice-entry.php'))?>">Fatura Girişi</a></header><?php if(isset($_GET['saved'])):?><p class="notice">Fatura kaydedildi.</p><?php endif?>
<form class="invoice-filter" method="get" autocomplete="off">
<div class="filter-text"><i class="ti tabler-search"></i><input name="q" value="<?=e($filterText)?>" placeholder="Stok, cari, fatura no veya tarih ara"></div>
<div class="filter-company"><span>Firma</span><div class="filter-control"><input type="hidden" name="account_id" id="invoice-account-id" value="<?=$filterAccountId?>"><input id="invoice-account" value="<?=e($selectedAccountName)?>"><button type="button" class="filter-clear" data-clear="account" aria-label="Firmayı temizle">×</button><div id="invoice-account-results" class="filter-results"></div></div></div>
<div class="column-picker"><button type="button" class="column-trigger"><i class="ti tabler-columns-3"></i>Sütunlar</button><div class="column-menu"><div class="column-options"></div></div></div>
<div class="filter-dates"><label>Başlangıç Tarihi<div class="filter-control"><input type="date" name="date_start" value="<?=e($filterDateStart)?>"><button type="button" class="filter-clear" data-clear="date_start" aria-label="Başlangıç tarihini temizle">×</button></div></label><label>Bitiş Tarihi<div class="filter-control"><input type="date" name="date_end" value="<?=e($filterDateEnd)?>"><button type="button" class="filter-clear" data-clear="date_end" aria-label="Bitiş tarihini temizle">×</button></div></label></div>
</form>
<div class="wrap"><table><thead><tr><th>FATURA NO</th><th><a class="date-sort" href="<?=e(url('invoice-list.php?'.$sortQuery))?>">TARİH <i class="ti <?=$dateSort==='asc'?'tabler-sort-ascending':'tabler-sort-descending'?>"></i></a></th><th>HAREKET YÖNÜ</th><th>CARİ</th><th>KALEM</th><th>ALIŞ TOPLAMI</th><th>İŞLEM</th></tr></thead><tbody><?php foreach($invoices as $invoice):?><tr><td><?=e($invoice['invoice_no'])?></td><td><?=e(format_date_tr($invoice['movement_date']))?></td><td><b class="<?=$invoice['movement_type']==='Giriş'?'in':'out'?>"><?=e($invoice['movement_type'])?></b></td><td><?=e((string)$invoice['account_name'])?></td><td><?=$invoice['line_count']?></td><td><?=e(number_format((float)$invoice['total'],2,',','.'))?> TL</td><td><?php if($invoice['movement_type']==='Giriş'):?><a class="edit" href="<?=e(url('invoice-entry.php?edit_invoice='.rawurlencode((string)$invoice['invoice_no'])))?>">Düzenle</a><?php else:?>—<?php endif?></td></tr><?php endforeach;if(!$invoices):?><tr><td colspan="7">Fatura bulunamadı.</td></tr><?php endif?></tbody></table></div></section></main>
<style>
.inv-list{max-width:1500px;margin:30px auto;padding:0 18px}.inv-list section{border:1px solid #e1e2e8;border-radius:10px;background:#fff;overflow:hidden}.inv-list>section>header{display:flex;align-items:center;gap:18px;padding:22px 24px;border-bottom:1px solid #e1e2e8}.inv-list>section>header>a{margin-left:auto;padding:10px 15px;border-radius:7px;background:#19a94b;color:#fff;text-decoration:none;font-weight:600}.inv-list h1{margin:0 0 5px}.inv-list p{margin:0;color:#7b7b8d}.notice{margin:14px 24px!important;padding:10px;background:#dff6e6;color:#147736!important}.wrap{overflow:auto}.inv-list table{width:100%;min-width:1000px;border-collapse:collapse}.inv-list th,.inv-list td{padding:14px 18px;border-bottom:1px solid #e1e2e8;text-align:left}.inv-list th{font-size:12px}.date-sort{display:inline-flex;align-items:center;gap:4px;color:inherit;text-decoration:none}.date-sort:hover{color:#19a94b}.in{color:#e04f55}.out{color:#19a94b}.edit{color:#19a94b;text-decoration:none;font-weight:600}
.invoice-filter{display:flex;align-items:center;gap:28px;padding:14px 24px;border-bottom:1px solid #e1e2e8;font-size:12px}.filter-text{display:flex;align-items:center;gap:10px;width:300px;color:#6f7180}.filter-text input,.filter-control input{box-sizing:border-box;width:100%;height:34px;padding:0 28px 0 10px;border:1px solid #d7d9e2;border-radius:6px;background:#fff;font:inherit;font-size:12px}.filter-company{display:flex;align-items:center;gap:10px;width:300px}.filter-company>span{white-space:nowrap;color:#5d5b6d}.filter-control{position:relative;flex:1;min-width:0}.filter-clear{position:absolute;top:50%;right:7px;width:16px!important;min-width:16px!important;height:16px!important;min-height:16px!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;color:#76798a!important;font:700 16px/16px Arial!important;transform:translateY(-50%);cursor:pointer!important;box-shadow:none!important}.filter-results{position:absolute;z-index:50;top:calc(100% + 3px);right:0;left:0;display:none;max-height:205px;overflow:auto;border:1px solid #d7d9e2;border-radius:6px;background:#fff;box-shadow:0 8px 18px rgba(47,43,61,.15)}.filter-results.open{display:block}.filter-results button{display:block;width:100%;padding:8px 10px;border:0;background:#fff;text-align:left;font:12px/1.35 inherit;cursor:pointer}.filter-results button:hover{background:#eef9f1}.filter-dates{display:flex;align-items:end;gap:10px;margin-left:auto}.filter-dates label{display:flex;flex-direction:column;gap:4px;width:160px;color:#5d5b6d}.column-picker{position:relative;margin-left:auto}.column-trigger{display:inline-flex;align-items:center;gap:6px;height:34px;padding:0 12px;border:0;border-radius:6px;background:#18a84b;color:#fff;font-weight:600;cursor:pointer}.column-menu{position:absolute;z-index:80;top:calc(100% + 7px);right:0;display:none;width:210px;padding:8px;border:1px solid #dfe1e8;border-radius:7px;background:#fff;box-shadow:0 10px 22px rgba(47,43,61,.18)}.column-menu.open{display:block}.column-option{display:flex;align-items:center;gap:7px;padding:5px 2px;cursor:pointer}.column-option input{width:15px;height:15px;accent-color:#18a84b}@media(max-width:1000px){.invoice-filter{flex-wrap:wrap;gap:14px}.column-picker,.filter-dates{margin-left:0}}
</style>
<script>
(()=>{const accounts=<?=json_encode($accounts,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,form=document.querySelector('.invoice-filter'),input=document.getElementById('invoice-account'),accountId=document.getElementById('invoice-account-id'),results=document.getElementById('invoice-account-results'),close=()=>{results.replaceChildren();results.classList.remove('open')},choose=account=>{accountId.value=String(account.id);input.value=account.short_name||account.title;close()};input.addEventListener('input',()=>{accountId.value='';const term=input.value.trim().toLocaleLowerCase('tr-TR');if(term.length<2){close();return}const found=accounts.filter(a=>((a.short_name||'')+' '+a.title).toLocaleLowerCase('tr-TR').includes(term)).slice(0,8);results.replaceChildren(...found.map(a=>{const b=document.createElement('button');b.type='button';b.textContent=a.short_name||a.title;b.onclick=()=>choose(a);return b}));results.classList.toggle('open',found.length>0)});document.addEventListener('click',event=>{if(!event.target.closest('.filter-company'))close()});form.querySelector('[data-clear="account"]').onclick=()=>{input.value='';accountId.value='';close();input.focus()};form.querySelectorAll('[data-clear="date_start"],[data-clear="date_end"]').forEach(button=>button.onclick=()=>{const field=form.querySelector('[name="'+button.dataset.clear+'"]');field.value='';field.focus()});form.addEventListener('submit',event=>{if(input.value.trim()&&!accountId.value){event.preventDefault();input.focus()}});
const table=document.querySelector('.inv-list table'),menu=document.querySelector('.column-menu'),options=document.querySelector('.column-options'),trigger=document.querySelector('.column-trigger'),headers=[...table.tHead.rows[0].cells],key='vox-invoice-list-columns';let visible;try{visible=JSON.parse(localStorage.getItem(key)||'null')}catch(e){}if(!Array.isArray(visible)||visible.length!==headers.length)visible=headers.map(()=>true);const apply=()=>{table.querySelectorAll('tr').forEach(row=>[...row.children].forEach((cell,i)=>cell.style.display=visible[i]?'':'none'));localStorage.setItem(key,JSON.stringify(visible))};options.replaceChildren(...headers.map((header,i)=>{const label=document.createElement('label'),checkbox=document.createElement('input');label.className='column-option';checkbox.type='checkbox';checkbox.checked=visible[i];checkbox.onchange=()=>{visible[i]=checkbox.checked;apply()};label.append(checkbox,document.createTextNode(header.textContent.trim()));return label}));trigger.onclick=()=>menu.classList.toggle('open');document.addEventListener('click',event=>{if(!event.target.closest('.column-picker'))menu.classList.remove('open')});apply()})();
</script>
<script>
(()=>{const form=document.querySelector('.invoice-filter');if(!form)return;const submit=()=>HTMLFormElement.prototype.submit.call(form),query=form.querySelector('input[name="q"]'),company=document.getElementById('invoice-account'),companyId=document.getElementById('invoice-account-id'),accounts=<?=json_encode($accounts,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,matches=()=>{const term=company.value.trim().toLocaleLowerCase('tr-TR');return term.length<2?[]:accounts.filter(account=>((account.short_name||'')+' '+account.title).toLocaleLowerCase('tr-TR').includes(term))},selectAndSubmit=account=>{companyId.value=String(account.id);company.value=account.short_name||account.title;submit()};let searchTimer,companyTimer;query?.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(submit,500)});query?.addEventListener('keydown',event=>{if(event.key!=='Enter')return;event.preventDefault();clearTimeout(searchTimer);submit()});company?.addEventListener('input',()=>{clearTimeout(companyTimer);companyTimer=setTimeout(()=>{const found=matches();if(found.length===1)selectAndSubmit(found[0])},500)});company?.addEventListener('keydown',event=>{if(event.key!=='Enter')return;event.preventDefault();clearTimeout(companyTimer);const found=matches();if(found.length)selectAndSubmit(found[0])});form.querySelector('.filter-results')?.addEventListener('click',event=>{if(event.target.closest('button'))setTimeout(submit,0)});form.querySelectorAll('input[type="date"]').forEach(field=>field.addEventListener('change',submit));form.querySelectorAll('.filter-clear').forEach(button=>button.addEventListener('click',()=>setTimeout(submit,0)))})();
</script>
<?php patient_footer();
