<?php
declare(strict_types=1);
require __DIR__.'/config.php'; require_login(); require __DIR__.'/patient-layout.php';
$pdo=db();
function invoice_amount(string $value):float{$value=str_replace(' ','',trim($value));return (float)(str_contains($value,',')?str_replace(',','.',str_replace('.','',$value)):str_replace('.','',$value));}
$stocks=$pdo->query('SELECT id,stock_code,stock_name,stock_type,brand,vat_rate,sale_price FROM stock_cards ORDER BY stock_name,stock_code')->fetchAll();
$accounts=$pdo->query("SELECT id,code,title,short_name FROM current_accounts WHERE account_type IN ('supplier','both') ORDER BY title")->fetchAll();
$error='';$form=['account_id'=>'','invoice_no'=>'','movement_date'=>date('Y-m-d')];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();foreach($form as $key=>$value)$form[$key]=trim((string)($_POST[$key]??$value));$accountId=filter_var($form['account_id'],FILTER_VALIDATE_INT);$rows=(array)($_POST['rows']??[]);if(!$accountId||$form['invoice_no']===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$form['movement_date'])||!$rows)$error='Cari, fatura no, tarih ve en az bir kalem zorunludur.';else{$existing=$pdo->prepare('SELECT movement_date FROM stock_movements WHERE movement_type="Giriş" AND LOWER(TRIM(invoice_no))=LOWER(TRIM(?)) LIMIT 1');$existing->execute([$form['invoice_no']]);$date=$existing->fetchColumn();if($date!==false&&$date!==$form['movement_date'])$error='Bu fatura numarası için giriş tarihi '.format_date_tr((string)$date).' olmalıdır.';}
if($error===''){try{$pdo->beginTransaction();$stockQuery=$pdo->prepare('SELECT id,stock_type,vat_rate FROM stock_cards WHERE id=?');$insert=$pdo->prepare('INSERT INTO stock_movements(stock_id,movement_type,quantity,unit,movement_date,current_account_id,invoice_no,purchase_price,sale_price,vat_rate,unit_cost,serial_numbers) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$update=$pdo->prepare('UPDATE stock_cards SET purchase_price=?,sale_price=?,vat_rate=?,unit_cost=? WHERE id=?');foreach($rows as $row){$stockId=filter_var($row['stock_id']??null,FILTER_VALIDATE_INT);$qty=filter_var($row['quantity']??null,FILTER_VALIDATE_INT);$unit=in_array($row['unit']??'', ['Adet','Kutu','Kg'],true)?$row['unit']:'';$cost=invoice_amount((string)($row['unit_cost']??''));$sale=invoice_amount((string)($row['sale_price']??''));if(!$stockId||!$qty||$qty<1||$unit===''||$cost<0||$sale<0)throw new RuntimeException('Her satırda stok kartı, miktar, birim, birim fiyatı ve satış fiyatı girin.');$stockQuery->execute([$stockId]);$stock=$stockQuery->fetch();if(!$stock)throw new RuntimeException('Geçersiz stok kartı.');$total=$cost*$qty;$vat=(float)($stock['vat_rate']??0);$update->execute([$total,$sale,$vat,$cost,$stockId]);$insert->execute([$stockId,'Giriş',$qty,$unit,$form['movement_date'],$accountId,$form['invoice_no'],$total,$sale,$vat,$cost,'[]']);}$pdo->commit();header('Location: '.url('stock-entry.php?saved=1'));exit;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}}}
patient_header('Fatura Girişi','stock');
?>
<main class="patient-container invoice-entry"><section class="vuexy-form-card"><header><h1>Fatura Girişi</h1><p>Fatura bilgilerini bir kez girin, kalemleri satır satır ekleyin.</p></header><?php if($error):?><p class="error"><?=e($error)?></p><?php endif?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><div class="invoice-head"><label>Cari *<select name="account_id" required><option value="">Seçiniz</option><?php foreach($accounts as $a):?><option value="<?=$a['id']?>" <?=$form['account_id']==$a['id']?'selected':''?>><?=e($a['code'].' — '.($a['short_name']?:$a['title']))?></option><?php endforeach?></select></label><label>Fatura No *<input name="invoice_no" required value="<?=e($form['invoice_no'])?>"></label><label>Giriş Tarihi *<input type="date" name="movement_date" required value="<?=e($form['movement_date'])?>"></label></div><table><thead><tr><th>Stok Kartı</th><th>Miktar</th><th>Birim</th><th>Birim Fiyatı</th><th>Alış Toplamı</th><th>Satış Fiyatı</th><th></th></tr></thead><tbody id="rows"></tbody></table><div class="actions"><button type="button" id="add">+ Satır Ekle</button><a href="<?=e(url('stock-entry.php'))?>">İptal</a><button class="button">Faturayı Kaydet</button></div></form></section></main>
<script>const stocks=<?=json_encode($stocks,JSON_UNESCAPED_UNICODE)?>,rows=document.getElementById('rows'),money=n=>new Intl.NumberFormat('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n||0),parse=v=>Number(String(v).replaceAll('.','').replace(',','.'))||0;function add(){const i=rows.children.length,r=document.createElement('tr');r.innerHTML='<td><select name="rows['+i+'][stock_id]" required><option value="">Seçiniz</option>'+stocks.map(s=>'<option value="'+s.id+'">'+s.stock_code+' — '+s.stock_name+'</option>').join('')+'</select></td><td><input name="rows['+i+'][quantity]" type="number" min="1" value="1" required></td><td><select name="rows['+i+'][unit]"><option>Adet</option><option>Kutu</option><option>Kg</option></select></td><td><input name="rows['+i+'][unit_cost]" inputmode="decimal" value="0,00" required></td><td class="total">0,00 TL</td><td><input name="rows['+i+'][sale_price]" inputmode="decimal" value="0,00" required></td><td><button type="button">×</button></td>';const calc=()=>r.querySelector('.total').textContent=money(parse(r.querySelector('[name*=unit_cost]').value)*Number(r.querySelector('[name*=quantity]').value||0))+' TL';r.querySelectorAll('input').forEach(x=>x.addEventListener('input',calc));r.querySelector('button').onclick=()=>{if(rows.children.length>1)r.remove()};rows.append(r)}document.getElementById('add').onclick=add;add();</script>
<style>.invoice-entry{max-width:1300px;margin:30px auto}.invoice-entry section{background:#fff;border:1px solid #e1e2e8;border-radius:10px;padding:24px}.invoice-entry h1{margin:0}.invoice-head{display:grid;grid-template-columns:2fr 1fr 1fr;gap:16px;margin:22px 0}.invoice-entry label{display:flex;flex-direction:column;gap:6px}.invoice-entry input,.invoice-entry select{height:40px;padding:0 10px;border:1px solid #d5d3de;border-radius:6px;font:inherit}.invoice-entry table{width:100%;border-collapse:collapse}.invoice-entry th,.invoice-entry td{padding:8px;border-bottom:1px solid #e1e2e8;text-align:left}.invoice-entry td:first-child{width:38%}.invoice-entry td input,.invoice-entry td select{width:100%;box-sizing:border-box}.actions{display:flex;justify-content:flex-end;gap:12px;margin-top:20px}.error{padding:10px;background:#ffe3e3;color:#a21d1d}@media(max-width:720px){.invoice-head{grid-template-columns:1fr}.invoice-entry{margin:12px}.invoice-entry table{display:block;overflow:auto;white-space:nowrap}}</style>
<?php patient_footer();?>
