<?php
require __DIR__.'/config.php';require_login();$id=(int)($_GET['id']??$_POST['id']??0);$stmt=db()->prepare('SELECT * FROM items WHERE id=?');$stmt->execute([$id]);$item=$stmt->fetch();if(!$item){http_response_code(404);exit('Kayıt bulunamadı.');}$error='';
$locations=db()->query('SELECT name FROM location_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$departments=db()->query('SELECT name FROM department_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$storages=db()->query('SELECT name FROM storage_definitions WHERE active=1 ORDER BY sort_order,name')->fetchAll();$itemDefinitions=db()->query('SELECT id,category,name FROM item_definitions WHERE active=1 ORDER BY sort_order,category,name')->fetchAll();$statuses=['Eşleşme bekliyor','Talep sahibinden eylem bekliyor','Yetkilendirilmiş kişi bekleniyor','Teslim edildi','Teslim edildi (Görüşüldü)','Depoda','Kargolandı','Tasfiye edildi'];
$currentDefinition=null;foreach($itemDefinitions as $definition)if($definition['category']===$item['category']&&$definition['name']===$item['name']){$currentDefinition=(string)$definition['id'];break;}$definitionValue=$_POST['item_definition']??($currentDefinition??'current');
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();foreach(['item_no','found_at','location','found_department','item_definition','storage_location','status'] as $key)if(trim($_POST[$key]??'')==='')$error='Zorunlu alanları doldurun.';
 $category=$item['category'];$name=$item['name'];if(!$error&&$_POST['item_definition']!=='current'){$s=db()->prepare('SELECT category,name FROM item_definitions WHERE id=? AND active=1');$s->execute([(int)$_POST['item_definition']]);$selected=$s->fetch();if(!$selected)$error='Geçerli bir eşya seçin.';else{$category=$selected['category'];$name=$selected['name'];}}
 if(!$error){$sql='UPDATE items SET item_no=?,serial_no=?,related_items=?,found_at=?,location=?,found_department=?,found_by=?,quantity=?,category=?,name=?,brand=?,color=?,details=?,storage_location=?,status=?,delivered_at=?,delivery_method=?,delivered_by=?,delivery_form_no=? WHERE id=?';$values=[trim($_POST['item_no']),trim($_POST['serial_no']??''),trim($_POST['related_items']??''),$_POST['found_at'],trim($_POST['location']),trim($_POST['found_department']),trim($_POST['found_by']??''),max(1,(int)($_POST['quantity']??1)),$category,$name,trim($_POST['brand']??''),trim($_POST['color']??''),trim($_POST['details']??''),trim($_POST['storage_location']),trim($_POST['status']),($_POST['delivered_at']??'')?:null,trim($_POST['delivery_method']??''),trim($_POST['delivered_by']??''),trim($_POST['delivery_form_no']??''),$id];try{$stmt=db()->prepare($sql);$stmt->execute($values);redirect('index.php');}catch(PDOException $e){$error='Kayıt güncellenemedi. Eşya numarası benzersiz olmalıdır.';}}
}
function field(string $key):string{return e($_POST[$key]??$GLOBALS['item'][$key]??'');}
function chosen(string $value,string $current):string{return $value===$current?'selected':'';}
$deliveredValue=$_POST['delivered_at']??($item['delivered_at']?date('Y-m-d\TH:i',strtotime($item['delivered_at'])):'');
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Eşya Düzenle | <?=APP_NAME?></title><link rel="icon" href="<?=url('assets/favicon.png')?>"><link rel="stylesheet" href="<?=url('assets/style.css')?>"><link rel="stylesheet" href="<?=url('assets/item-new.css')?>"><link rel="stylesheet" href="<?=url('assets/entry.css')?>"><link rel="stylesheet" href="<?=url('assets/required.css')?>"><link rel="stylesheet" href="<?=url('assets/home-link.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/fonts/fonts.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/css/bootstrap.min.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce/css/styles.css')?>"><link rel="stylesheet" href="<?=url('assets/amerce-lf.css')?>"><link rel="stylesheet" href="<?=url('assets/vuexy-inspired.css')?>"><link rel="stylesheet" href="<?=url('assets/green-buttons.css?v=20260712-3')?>"><script src="<?=url('assets/theme.js?v=20260712-2')?>"></script></head><body>
<header><a class="brand brand-back-link" href="<?=url('index.php')?>" onclick="if(document.referrer&&history.length>1){history.back();return false}" title="Önceki sayfaya dön"><img class="entry-brand-logo" style="display:block!important;width:38px!important;min-width:38px!important;max-width:38px!important;height:38px!important;min-height:38px!important;max-height:38px!important;object-fit:contain!important" src="<?=url('assets/kirpisoftware-logo-transparent-v2.png')?>" alt="Kirpisoft"><span><b>Lost &amp; Found</b></span></a><a class="home-link" href="<?=url('index.php')?>" title="Ana sayfa" aria-label="Ana sayfa">⌂</a></header>
<main class="container entry-container"><div class="entry-title"><h1>Eşya Düzenle</h1><p><?=e($item['item_no'])?> numaralı eşyanın tüm bilgilerini güncelleyin.</p></div><?php if($error):?><div class="alert"><?=e($error)?></div><?php endif?>
<form id="item-form" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$id?>"><section class="entry-panel"><div class="entry-grid">
<label>Eşya *<div class="search-select" data-search-select><input type="hidden" name="item_definition" value="<?=e($definitionValue)?>" required><button class="search-select-trigger" type="button" aria-haspopup="listbox" aria-expanded="false"><span><?=e($item['category'].' - '.$item['name'])?></span><i></i></button><div class="search-select-menu"><input class="search-select-input" type="search" placeholder="Eşya ara..." autocomplete="off"><div class="search-select-options" role="listbox"><?php if(!$currentDefinition):?><button type="button" role="option" data-value="current" data-label="<?=e($item['category'].' - '.$item['name'])?>"><?=e($item['category'].' - '.$item['name'])?></button><?php endif?><?php foreach($itemDefinitions as $d):$label=$d['category'].' - '.$d['name'];?><button type="button" role="option" data-value="<?=(int)$d['id']?>" data-label="<?=e($label)?>"><?=e($label)?></button><?php endforeach?><p class="search-select-empty">Sonuç bulunamadı.</p></div></div></div></label>
<label>Eşya no *<input name="item_no" value="<?=field('item_no')?>" required></label><label>Seri no<input name="serial_no" value="<?=field('serial_no')?>"></label><label>İlgili eşyalar<input name="related_items" value="<?=field('related_items')?>"></label>
<label>Bulunduğu yer *<select name="location" required><option value="">Yer seçiniz</option><?php foreach($locations as $v):?><option <?=chosen($v['name'],$_POST['location']??$item['location'])?>><?=e($v['name'])?></option><?php endforeach?></select></label><label>Bulunduğu tarih *<input type="date" name="found_at" value="<?=field('found_at')?>" required></label>
<label>Bulan departman *<select name="found_department" required><option value="">Departman seçiniz</option><?php foreach($departments as $v):?><option <?=chosen($v['name'],$_POST['found_department']??$item['found_department'])?>><?=e($v['name'])?></option><?php endforeach?></select></label><label>Bulan bilgisi<input name="found_by" value="<?=field('found_by')?>"></label><label>Kaydeden<input value="<?=e($item['recorded_by'])?>" readonly></label>
<label>Marka<input name="brand" value="<?=field('brand')?>"></label><label>Renk<input name="color" value="<?=field('color')?>"></label><label>Miktar<input type="number" name="quantity" min="1" value="<?=field('quantity')?>"></label>
<label>Depo *<select name="storage_location" required><option value="">Depo seçiniz</option><?php foreach($storages as $v):?><option <?=chosen($v['name'],$_POST['storage_location']??$item['storage_location'])?>><?=e($v['name'])?></option><?php endforeach?></select></label><label>Durum *<select name="status" required><?php foreach($statuses as $status):?><option <?=chosen($status,$_POST['status']??$item['status'])?>><?=e($status)?></option><?php endforeach?></select></label>
<label>Teslimat tarihi<input type="datetime-local" name="delivered_at" value="<?=e($deliveredValue)?>"></label><label>Teslim şekli<input name="delivery_method" value="<?=field('delivery_method')?>"></label><label>Teslim eden<input name="delivered_by" value="<?=field('delivered_by')?>"></label><label>Teslim form no<input name="delivery_form_no" value="<?=field('delivery_form_no')?>"></label>
<label class="details-field">Açıklama<textarea name="details" rows="2"><?=field('details')?></textarea></label>
</div></section><div class="entry-actions"><a class="button secondary" href="<?=url('index.php')?>">Vazgeç</a><button class="save-button" type="submit">Kaydet</button></div></form></main>
<script>document.querySelectorAll('[data-search-select]').forEach(select=>{const hidden=select.querySelector('input[type=hidden]'),trigger=select.querySelector('.search-select-trigger'),caption=trigger.querySelector('span'),search=select.querySelector('.search-select-input'),options=[...select.querySelectorAll('[role=option]')],empty=select.querySelector('.search-select-empty');const selected=options.find(o=>o.dataset.value===hidden.value);if(selected){caption.textContent=selected.dataset.label;selected.setAttribute('aria-selected','true')}const close=()=>{select.classList.remove('open');trigger.setAttribute('aria-expanded','false')};trigger.addEventListener('click',()=>{const opening=!select.classList.contains('open');select.classList.toggle('open',opening);trigger.setAttribute('aria-expanded',String(opening));if(opening){search.value='';options.forEach(o=>o.hidden=false);empty.hidden=true;search.focus()}});search.addEventListener('input',()=>{const term=search.value.toLocaleLowerCase('tr-TR').trim();let visible=0;options.forEach(o=>{o.hidden=!o.dataset.label.toLocaleLowerCase('tr-TR').includes(term);if(!o.hidden)visible++});empty.hidden=visible!==0});options.forEach(o=>o.addEventListener('click',()=>{hidden.value=o.dataset.value;caption.textContent=o.dataset.label;options.forEach(x=>x.setAttribute('aria-selected',String(x===o)));close()}));document.addEventListener('click',e=>{if(!select.contains(e.target))close()})});</script><script src="<?=url('assets/required.js')?>"></script></body></html>
