<?php
require __DIR__.'/config.php';require_admin();$id=(int)($_GET['id']??$_POST['id']??0);$stmt=db()->prepare("SELECT id,name,email,role,active FROM users WHERE id=?");$stmt->execute([$id]);$target=$stmt->fetch();if(!$target){http_response_code(404);exit('Kullanıcı bulunamadı.');}if($id===(int)$_SESSION['user']['id']){redirect('profile.php');}if(normalize_role((string)$target['role'])===ROLE_COMPANY_MANAGER){http_response_code(403);exit('Firma yöneticisi bu ekrandan düzenlenemez.');}$key='profile_'.$id;$p=db()->prepare('SELECT setting_value FROM settings WHERE setting_key=?');$p->execute([$key]);$profile=json_decode((string)$p->fetchColumn(),true)?:[];$profile=array_merge(['phone'=>'','organization'=>'','address'=>'','state'=>'','zip_code'=>'','country'=>'Türkiye','language'=>'Türkçe','timezone'=>'Europe/Istanbul','currency'=>'TRY','avatar'=>''],$profile);$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';
 if($action==='profile'){$name=trim($_POST['name']??'');$email=trim(strtolower($_POST['email']??''));$active=isset($_POST['active'])?1:0;if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL))$error='Geçerli ad ve e-posta girin.';else{$check=db()->prepare('SELECT id FROM users WHERE LOWER(email)=LOWER(?) AND id<>? LIMIT 1');$check->execute([$email,$id]);if($check->fetch())$error='Bu e-posta adresi başka bir kullanıcı tarafından kullanılıyor. Aynı e-posta ile ikinci kullanıcı olamaz.';else try{$update=db()->prepare("UPDATE users SET name=?,email=?,active=? WHERE id=? AND role IN ('User','secretary','audiometrist','accounting')");$update->execute([$name,$email,$active,$id]);foreach(['phone','organization','address','state','zip_code','country','language','timezone','currency'] as $field)$profile[$field]=trim($_POST[$field]??'');$driver=db()->getAttribute(PDO::ATTR_DRIVER_NAME);$sql=$driver==='mysql'?'INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)':'INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value';db()->prepare($sql)->execute([$key,json_encode($profile,JSON_UNESCAPED_UNICODE)]);$target['name']=$name;$target['email']=$email;$target['active']=$active;$message='Kullanıcı profili güncellendi.';}catch(PDOException $e){$error='Bu e-posta adresi başka bir kullanıcı tarafından kullanılıyor. Aynı e-posta ile ikinci kullanıcı olamaz.';}}}
 if($action==='password'){$password=$_POST['password']??'';$confirm=$_POST['password_confirm']??'';if(strlen($password)<6)$error='Şifre en az 6 karakter olmalıdır.';elseif($password!==$confirm)$error='Şifre ve şifre tekrarı aynı olmalıdır.';else{$update=db()->prepare("UPDATE users SET password_hash=? WHERE id=? AND role IN ('User','secretary','audiometrist','accounting')");$update->execute([password_hash($password,PASSWORD_DEFAULT),$id]);$message='Kullanıcının şifresi değiştirildi.';}}
}
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kullanıcı Düzenle | <?=APP_NAME?></title><link rel="icon" href="<?=url('assets/favicon.png')?>"><link rel="stylesheet" href="<?=url('assets/style.css')?>"><link rel="stylesheet" href="<?=url('assets/admin.css')?>"><link rel="stylesheet" href="<?=url('assets/profile.css')?>"><link rel="stylesheet" href="<?=url('assets/green-buttons.css?v=20260712-4')?>"><script src="<?=url('assets/theme.js?v=20260712-2')?>"></script><style>
body.vox-user-editor{margin:0!important;background:#dcebf8!important;color:#12354b!important;font-family:Arial,sans-serif!important;font-size:12px!important}
body.vox-user-editor>header{display:none!important}
body.vox-user-editor .profile-container{box-sizing:border-box!important;width:100%!important;max-width:none!important;padding:8px!important;margin:0!important}
body.vox-user-editor .title-row{margin:0 0 8px!important;padding:6px 8px!important}
body.vox-user-editor .title-row h1{font-size:15px!important;margin:0 0 3px!important}
body.vox-user-editor .title-row p{font-size:12px!important;margin:0!important}
body.vox-user-editor .profile-card{padding:8px!important;margin:0 0 10px!important;background:#edf5fc!important;border:1px solid #80ace0!important;border-radius:0!important;box-shadow:none!important}
body.vox-user-editor .profile-card h2{font-size:13px!important;color:#12558a!important;padding:5px 7px!important;margin:-8px -8px 8px!important;border-bottom:1px solid #80ace0!important;background:linear-gradient(#f5faff,#cbe1f8)!important}
body.vox-user-editor .profile-form,body.vox-user-editor .password-form{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px 12px!important;margin:0!important}
body.vox-user-editor form label{min-width:0!important;font-size:12px!important;font-weight:600!important;display:flex!important;flex-direction:column!important;gap:3px!important}
body.vox-user-editor form input:not([type=hidden]):not([type=checkbox]){box-sizing:border-box!important;width:100%!important;height:27px!important;min-height:27px!important;padding:3px 6px!important;margin:0!important;border:1px solid #80ace0!important;border-radius:0!important;background:#fff!important;color:#12354b!important;font-size:12px!important}
body.vox-user-editor form .active-user{flex-direction:row!important;align-items:center!important;align-self:end!important;height:27px!important}
body.vox-user-editor input[type=checkbox]{width:15px!important;height:15px!important;margin:0 5px 0 0!important}
body.vox-user-editor .profile-actions{grid-column:1/-1!important;display:flex!important;justify-content:flex-end!important;margin:0!important;padding-top:6px!important}
body.vox-user-editor button.save-profile{box-sizing:border-box!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;justify-self:end!important;grid-column:1/-1!important;width:auto!important;min-width:116px!important;max-width:none!important;height:32px!important;padding:0 12px!important;margin:0!important;white-space:nowrap!important;background:linear-gradient(#25b67b,#08744d)!important;color:#fff!important;border:1px solid #08744d!important;border-radius:3px!important;font-size:12px!important;line-height:normal!important;text-indent:0!important;overflow:visible!important}
@media(max-width:600px){body.vox-user-editor .profile-form,body.vox-user-editor .password-form{grid-template-columns:1fr!important}}
</style></head><body class="vox-user-editor"><header><div class="brand"><span class="brand-mark">K</span><span>KRP <b>Lost &amp; Found</b></span></div><a class="button secondary" href="<?=url('admin.php#kullanicilar')?>">Kullanıcılara dön</a></header><main class="profile-container"><section class="title-row"><div><h1><?=e($target['name'])?></h1><p>Kullanıcı profilini ve giriş şifresini yönetin.</p></div></section><?php if($message):?><div class="success"><?=e($message)?></div><?php endif?><?php if($error):?><div class="alert"><?=e($error)?></div><?php endif?><section class="profile-card"><h2>Profil Bilgileri</h2><form class="profile-form" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="profile"><label>Ad Soyad<input name="name" value="<?=e($target['name'])?>" required></label><label>E-posta<input type="email" name="email" value="<?=e($target['email'])?>" required></label><label>Telefon<input name="phone" value="<?=e($profile['phone'])?>"></label><label>Kurum<input name="organization" value="<?=e($profile['organization'])?>"></label><label>Adres<input name="address" value="<?=e($profile['address'])?>"></label><label>Şehir / İl<input name="state" value="<?=e($profile['state'])?>"></label><label>Posta Kodu<input name="zip_code" value="<?=e($profile['zip_code'])?>"></label><label>Ülke<input name="country" value="<?=e($profile['country'])?>"></label><label>Dil<input name="language" value="<?=e($profile['language'])?>"></label><label>Saat Dilimi<input name="timezone" value="<?=e($profile['timezone'])?>"></label><label>Para Birimi<input name="currency" value="<?=e($profile['currency'])?>"></label><label class="active-user"><input type="checkbox" name="active" value="1" <?=$target['active']?'checked':''?>> Kullanıcı aktif</label><div class="profile-actions"><button class="save-profile">Kaydet</button></div></form></section><section class="profile-card password-card"><h2>Şifre Değiştir</h2><form class="password-form" method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="password"><label>Yeni şifre<input type="password" name="password" minlength="6" autocomplete="new-password" required></label><label>Yeni şifre tekrar<input type="password" name="password_confirm" minlength="6" autocomplete="new-password" required></label><button class="save-profile">Kaydet</button></form></section></main></body></html>
