<?php
declare(strict_types=1);
putenv('APP_ENV=local');require __DIR__.'/config.php';
$pdo=db();$pdo->exec('DROP TABLE IF EXISTS patients');$pdo->exec('DROP TABLE IF EXISTS settings');$pdo->exec('DROP TABLE IF EXISTS users');
$pdo->exec("CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT,name VARCHAR(150) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role VARCHAR(20) NOT NULL DEFAULT 'User',active INTEGER NOT NULL DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP)");
$pdo->exec("CREATE TABLE settings (id INTEGER PRIMARY KEY AUTOINCREMENT,setting_key VARCHAR(190) NOT NULL UNIQUE,setting_value TEXT)");
$pdo->exec("CREATE TABLE patients (id INTEGER PRIMARY KEY AUTOINCREMENT,import_order INTEGER NOT NULL,record_date DATE NULL,full_name VARCHAR(190) NOT NULL,national_id VARCHAR(30),phone_primary VARCHAR(50),phone_secondary VARCHAR(50),birth_date DATE NULL,address TEXT,social_security VARCHAR(100),report_info VARCHAR(150),report_status TEXT NULL CHECK(report_status IN ('Rapor getirdi','Rapor getirecek','Rapor gerekmedi','Özel reçete getirdi','Özel reçete getirecek')),service_location VARCHAR(150),service_type VARCHAR(150),source_primary VARCHAR(150),source_marketing VARCHAR(150),source_detail VARCHAR(255),anamnesis TEXT,notes TEXT,approval INTEGER NOT NULL DEFAULT 0,considering INTEGER NOT NULL DEFAULT 0,rejected INTEGER NOT NULL DEFAULT 0,staff_cansu INTEGER NOT NULL DEFAULT 0,staff_busra INTEGER NOT NULL DEFAULT 0,staff_belma INTEGER NOT NULL DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)");
$st=$pdo->prepare('INSERT INTO users(name,email,password_hash,role,active) VALUES(?,?,?,?,1)');$st->execute(['Vox Yöneticisi','admin@sofitel.com',password_hash('112233',PASSWORD_DEFAULT),'Admin']);
$xlsx=__DIR__.'/storage/patients.xlsx';if(!is_file($xlsx))exit("Excel bulunamadı: $xlsx\n");if(!class_exists('ZipArchive'))exit("PHP ZipArchive eklentisi gerekli.\n");
$zip=new ZipArchive();if($zip->open($xlsx)!==true)exit("Excel açılamadı.\n");$shared=[];$sharedXml=$zip->getFromName('xl/sharedStrings.xml');if($sharedXml!==false){$sx=simplexml_load_string($sharedXml);foreach($sx->si as $si){$parts=[];if(isset($si->t))$parts[]=(string)$si->t;foreach($si->r as $run)$parts[]=(string)$run->t;$shared[]=implode('',$parts);}}
$sheet=simplexml_load_string($zip->getFromName('xl/worksheets/sheet1.xml'));$zip->close();function col_index(string $ref):int{preg_match('/^[A-Z]+/',$ref,$m);$n=0;foreach(str_split($m[0]) as $ch)$n=$n*26+ord($ch)-64;return $n;}$records=[];
foreach($sheet->sheetData->row as $row){$rn=(int)$row['r'];if($rn<4)continue;$v=array_fill(1,29,'');foreach($row->c as $c){$idx=col_index((string)$c['r']);$raw=(string)$c->v;$v[$idx]=((string)$c['t']==='s')?($shared[(int)$raw]??''):$raw;}if(trim($v[2])==='')continue;$excelDate=function($x){if($x===''||!is_numeric($x))return null;return gmdate('Y-m-d',(int)(($x-25569)*86400));};$records[]=[count($records)+1,$excelDate($v[1]),trim($v[2]),trim($v[3]),trim($v[4]),trim($v[5]),$excelDate($v[6]),trim($v[7]),trim($v[8]),trim($v[9]),trim($v[10]),trim($v[11]),trim($v[12]),trim($v[13]),trim($v[14]),trim($v[15]),trim($v[16]),$v[17]!==''?1:0,$v[18]!==''?1:0,$v[19]!==''?1:0,$v[21]!==''?1:0,$v[22]!==''?1:0,$v[23]!==''?1:0];}
$ins=$pdo->prepare('INSERT INTO patients(import_order,record_date,full_name,national_id,phone_primary,phone_secondary,birth_date,address,social_security,report_info,service_location,service_type,source_primary,source_marketing,source_detail,anamnesis,notes,approval,considering,rejected,staff_cansu,staff_busra,staff_belma) VALUES('.implode(',',array_fill(0,23,'?')).')');$pdo->beginTransaction();foreach($records as $r)$ins->execute($r);$pdo->commit();echo count($records)." hasta kaydı aktarıldı.\n";
